/****************************************************************************
 * arch/arm/src/ra8/hardware/ra8e1_pinmap.h
 *
 * GENERATED BY SCRIPT - DO NOT EDIT MANUALLY
 *
 ****************************************************************************/

#ifndef __ARCH_ARM_SRC_RA_HARDWARE_RA8E1_PINMAP_H
#define __ARCH_ARM_SRC_RA_HARDWARE_RA8E1_PINMAP_H

/****************************************************************************
 * Included Files
 ****************************************************************************/

#include <nuttx/config.h>
#include "chip.h"
#include "hardware/ra_memorymap.h"

/****************************************************************************
 * Pre-processor Definitions
 ****************************************************************************/

/* Alternative Function Pin Definitions */
#define GPIO_ADTRG0_1                         (gpio_pinset_t){ PORT1, PIN2, (PFS_PSEL_CAC_ADC14 | R_PFS_PMR)}
#define GPIO_ADTRG0_2                         (gpio_pinset_t){ PORT4, PIN7, (PFS_PSEL_CAC_ADC14 | R_PFS_PMR)}
#define GPIO_ADTRG1_1                         (gpio_pinset_t){ PORT2, PIN13, (PFS_PSEL_CAC_ADC14 | R_PFS_PMR)}
#define GPIO_ADTRG1_2                         (gpio_pinset_t){ PORT4, PIN0, (PFS_PSEL_CAC_ADC14 | R_PFS_PMR)}
#define GPIO_AGTEE0_1                         (gpio_pinset_t){ PORT1, PIN1, (PFS_PSEL_AGT | R_PFS_PMR)}
#define GPIO_AGTEE0_2                         (gpio_pinset_t){ PORT7, PIN11, (PFS_PSEL_AGT | R_PFS_PMR)}
#define GPIO_AGTEE1_1                         (gpio_pinset_t){ PORT2, PIN12, (PFS_PSEL_AGT | R_PFS_PMR)}
#define GPIO_AGTEE1_2                         (gpio_pinset_t){ PORT3, PIN10, (PFS_PSEL_AGT | R_PFS_PMR)}
#define GPIO_AGTEE1_3                         (gpio_pinset_t){ PORT4, PIN12, (PFS_PSEL_AGT | R_PFS_PMR)}
#define GPIO_AGTIO0_1                         (gpio_pinset_t){ PORT1, PIN0, (PFS_PSEL_AGT | R_PFS_PMR)}
#define GPIO_AGTIO0_2                         (gpio_pinset_t){ PORT3, PIN1, (PFS_PSEL_AGT | R_PFS_PMR)}
#define GPIO_AGTIO0_3                         (gpio_pinset_t){ PORT4, PIN7, (PFS_PSEL_AGT | R_PFS_PMR)}
#define GPIO_AGTIO0_4                         (gpio_pinset_t){ PORT7, PIN5, (PFS_PSEL_AGT | R_PFS_PMR)}
#define GPIO_AGTIO1_1                         (gpio_pinset_t){ PORT2, PIN4, (PFS_PSEL_AGT | R_PFS_PMR)}
#define GPIO_AGTIO1_2                         (gpio_pinset_t){ PORT4, PIN0, (PFS_PSEL_AGT | R_PFS_PMR)}
#define GPIO_AGTIO1_3                         (gpio_pinset_t){ PORT4, PIN5, (PFS_PSEL_AGT | R_PFS_PMR)}
#define GPIO_AGTO0_1                         (gpio_pinset_t){ PORT1, PIN2, (PFS_PSEL_AGT | R_PFS_PMR)}
#define GPIO_AGTO0_2                         (gpio_pinset_t){ PORT6, PIN14, (PFS_PSEL_AGT | R_PFS_PMR)}
#define GPIO_AGTO0_3                         (gpio_pinset_t){ PORT7, PIN4, (PFS_PSEL_AGT | R_PFS_PMR)}
#define GPIO_AGTO1_1                         (gpio_pinset_t){ PORT2, PIN5, (PFS_PSEL_AGT | R_PFS_PMR)}
#define GPIO_AGTO1_2                         (gpio_pinset_t){ PORT6, PIN13, (PFS_PSEL_AGT | R_PFS_PMR)}
#define GPIO_AGTO1_3                         (gpio_pinset_t){ PORT7, PIN3, (PFS_PSEL_AGT | R_PFS_PMR)}
#define GPIO_AGTOA0_1                         (gpio_pinset_t){ PORT1, PIN7, (PFS_PSEL_AGT | R_PFS_PMR)}
#define GPIO_AGTOA0_2                         (gpio_pinset_t){ PORT7, PIN13, (PFS_PSEL_AGT | R_PFS_PMR)}
#define GPIO_AGTOA0_3                         (gpio_pinset_t){ PORT8, PIN0, (PFS_PSEL_AGT | R_PFS_PMR)}
#define GPIO_AGTOA1_1                         (gpio_pinset_t){ PORT3, PIN12, (PFS_PSEL_AGT | R_PFS_PMR)}
#define GPIO_AGTOA1_2                         (gpio_pinset_t){ PORT4, PIN11, (PFS_PSEL_AGT | R_PFS_PMR)}
#define GPIO_AGTOB0_1                         (gpio_pinset_t){ PORT1, PIN6, (PFS_PSEL_AGT | R_PFS_PMR)}
#define GPIO_AGTOB0_2                         (gpio_pinset_t){ PORT7, PIN12, (PFS_PSEL_AGT | R_PFS_PMR)}
#define GPIO_AGTOB0_3                         (gpio_pinset_t){ PORT8, PIN1, (PFS_PSEL_AGT | R_PFS_PMR)}
#define GPIO_AGTOB1_1                         (gpio_pinset_t){ PORT3, PIN11, (PFS_PSEL_AGT | R_PFS_PMR)}
#define GPIO_AGTOB1_2                         (gpio_pinset_t){ PORT4, PIN10, (PFS_PSEL_AGT | R_PFS_PMR)}
#define GPIO_AUDIO_CLK_1                         (gpio_pinset_t){ PORT4, PIN0, (PFS_PSEL_CLKOUT_ACMPLP_RTC | R_PFS_PMR)}
#define GPIO_AUDIO_CLK_2                         (gpio_pinset_t){ PORT4, PIN2, (PFS_PSEL_CLKOUT_ACMPLP_RTC | R_PFS_PMR)}
#define GPIO_AUDIO_CLK_3                         (gpio_pinset_t){ PORT7, PIN8, (PFS_PSEL_CLKOUT_ACMPLP_RTC | R_PFS_PMR)}
#define GPIO_CRX0_1                         (gpio_pinset_t){ PORT1, PIN2, (PFS_PSEL_CAN | R_PFS_PMR)}
#define GPIO_CRX0_2                         (gpio_pinset_t){ PORT2, PIN2, (PFS_PSEL_CAN | R_PFS_PMR)}
#define GPIO_CRX0_3                         (gpio_pinset_t){ PORT3, PIN11, (PFS_PSEL_CAN | R_PFS_PMR)}
#define GPIO_CRX0_4                         (gpio_pinset_t){ PORT4, PIN2, (PFS_PSEL_CAN | R_PFS_PMR)}
#define GPIO_CRX0_5                         (gpio_pinset_t){ PORT7, PIN5, (PFS_PSEL_CAN | R_PFS_PMR)}
#define GPIO_CRX0_6                         (gpio_pinset_t){ PORT8, PIN14, (PFS_PSEL_CAN | R_PFS_PMR)}
#define GPIO_CRX1_1                         (gpio_pinset_t){ PORT2, PIN8, (PFS_PSEL_CAN | R_PFS_PMR)}
#define GPIO_CRX1_2                         (gpio_pinset_t){ PORT4, PIN14, (PFS_PSEL_CAN | R_PFS_PMR)}
#define GPIO_CRX1_3                         (gpio_pinset_t){ PORT5, PIN11, (PFS_PSEL_CAN | R_PFS_PMR)}
#define GPIO_CRX1_4                         (gpio_pinset_t){ PORT6, PIN10, (PFS_PSEL_CAN | R_PFS_PMR)}
#define GPIO_CTS0_A_1                         (gpio_pinset_t){ PORT1, PIN15, (PFS_PSEL_SCI | R_PFS_PMR)}
#define GPIO_CTS0_B_1                         (gpio_pinset_t){ PORT6, PIN5, (PFS_PSEL_SCI | R_PFS_PMR)}
#define GPIO_CTS0_C_1                         (gpio_pinset_t){ PORT6, PIN13, (PFS_PSEL_SCI | R_PFS_PMR)}
#define GPIO_CTS0_RTS0_A_SS0_A_1                         (gpio_pinset_t){ PORT1, PIN14, (PFS_PSEL_SCI | R_PFS_PMR)}
#define GPIO_CTS1_A_1                         (gpio_pinset_t){ PORT4, PIN4, (PFS_PSEL_SCI | R_PFS_PMR)}
#define GPIO_CTS1_B_1                         (gpio_pinset_t){ PORT7, PIN5, (PFS_PSEL_SCI | R_PFS_PMR)}
#define GPIO_CTS2_A_1                         (gpio_pinset_t){ PORT8, PIN0, (PFS_PSEL_SCI | R_PFS_PMR)}
#define GPIO_CTS2_B_1                         (gpio_pinset_t){ PORT7, PIN2, (PFS_PSEL_SCI | R_PFS_PMR)}
#define GPIO_CTS3_A_1                         (gpio_pinset_t){ PORT4, PIN12, (PFS_PSEL_SCI | R_PFS_PMR)}
#define GPIO_CTS3_B_1                         (gpio_pinset_t){ PORT9, PIN5, (PFS_PSEL_SCI | R_PFS_PMR)}
#define GPIO_CTS3_C_1                         (gpio_pinset_t){ PORT3, PIN13, (PFS_PSEL_SCI | R_PFS_PMR)}
#define GPIO_CTS4_A_1                         (gpio_pinset_t){ PORT4, PIN8, (PFS_PSEL_SCI | R_PFS_PMR)}
#define GPIO_CTS4_B_1                         (gpio_pinset_t){ PORT7, PIN10, (PFS_PSEL_SCI | R_PFS_PMR)}
#define GPIO_CTS9_A_1                         (gpio_pinset_t){ PORT1, PIN4, (PFS_PSEL_SCI | R_PFS_PMR)}
#define GPIO_CTS9_B_1                         (gpio_pinset_t){ PORT3, PIN8, (PFS_PSEL_SCI | R_PFS_PMR)}
#define GPIO_CTS9_RTS9_A_SS9_A_1                         (gpio_pinset_t){ PORT1, PIN3, (PFS_PSEL_SCI | R_PFS_PMR)}
#define GPIO_CTS_RTS0_B_SS0_B_1                         (gpio_pinset_t){ PORT6, PIN4, (PFS_PSEL_SCI | R_PFS_PMR)}
#define GPIO_CTS_RTS0_C_SS0_C_1                         (gpio_pinset_t){ PORT6, PIN12, (PFS_PSEL_SCI | R_PFS_PMR)}
#define GPIO_CTS_RTS2_A_SS2_A_1                         (gpio_pinset_t){ PORT8, PIN4, (PFS_PSEL_SCI | R_PFS_PMR)}
#define GPIO_CTS_RTS2_B_SS2_B_1                         (gpio_pinset_t){ PORT7, PIN1, (PFS_PSEL_SCI | R_PFS_PMR)}
#define GPIO_CTS_RTS3_A_SS3_A_1                         (gpio_pinset_t){ PORT4, PIN11, (PFS_PSEL_SCI | R_PFS_PMR)}
#define GPIO_CTS_RTS3_B_SS3_B_1                         (gpio_pinset_t){ PORT3, PIN12, (PFS_PSEL_SCI | R_PFS_PMR)}
#define GPIO_CTS_RTS4_A_SS4_A_1                         (gpio_pinset_t){ PORT4, PIN3, (PFS_PSEL_SCI | R_PFS_PMR)}
#define GPIO_CTS_RTS4_A_SS4_A_2                         (gpio_pinset_t){ PORT4, PIN7, (PFS_PSEL_SCI | R_PFS_PMR)}
#define GPIO_CTS_RTS4_B_SS4_B_1                         (gpio_pinset_t){ PORT7, PIN9, (PFS_PSEL_SCI | R_PFS_PMR)}
#define GPIO_CTS_RTS9_B_SS9_B_1                         (gpio_pinset_t){ PORT2, PIN10, (PFS_PSEL_SCI | R_PFS_PMR)}
#define GPIO_CTX0_1                         (gpio_pinset_t){ PORT1, PIN3, (PFS_PSEL_CAN | R_PFS_PMR)}
#define GPIO_CTX0_2                         (gpio_pinset_t){ PORT2, PIN3, (PFS_PSEL_CAN | R_PFS_PMR)}
#define GPIO_CTX0_3                         (gpio_pinset_t){ PORT3, PIN12, (PFS_PSEL_CAN | R_PFS_PMR)}
#define GPIO_CTX0_4                         (gpio_pinset_t){ PORT4, PIN1, (PFS_PSEL_CAN | R_PFS_PMR)}
#define GPIO_CTX0_5                         (gpio_pinset_t){ PORT7, PIN4, (PFS_PSEL_CAN | R_PFS_PMR)}
#define GPIO_CTX0_6                         (gpio_pinset_t){ PORT8, PIN15, (PFS_PSEL_CAN | R_PFS_PMR)}
#define GPIO_CTX1_1                         (gpio_pinset_t){ PORT2, PIN9, (PFS_PSEL_CAN | R_PFS_PMR)}
#define GPIO_CTX1_2                         (gpio_pinset_t){ PORT4, PIN15, (PFS_PSEL_CAN | R_PFS_PMR)}
#define GPIO_CTX1_3                         (gpio_pinset_t){ PORT5, PIN12, (PFS_PSEL_CAN | R_PFS_PMR)}
#define GPIO_CTX1_4                         (gpio_pinset_t){ PORT6, PIN9, (PFS_PSEL_CAN | R_PFS_PMR)}
#define GPIO_DE0_1                         (gpio_pinset_t){ PORT1, PIN14, (PFS_PSEL_SCI | R_PFS_PMR)}
#define GPIO_DE0_2                         (gpio_pinset_t){ PORT3, PIN0, (PFS_PSEL_SCI | R_PFS_PMR)}
#define GPIO_DE0_3                         (gpio_pinset_t){ PORT6, PIN1, (PFS_PSEL_SCI | R_PFS_PMR)}
#define GPIO_DE0_4                         (gpio_pinset_t){ PORT6, PIN4, (PFS_PSEL_SCI | R_PFS_PMR)}
#define GPIO_DE0_5                         (gpio_pinset_t){ PORT6, PIN11, (PFS_PSEL_SCI | R_PFS_PMR)}
#define GPIO_DE0_6                         (gpio_pinset_t){ PORT6, PIN12, (PFS_PSEL_SCI | R_PFS_PMR)}
#define GPIO_DE1_1                         (gpio_pinset_t){ PORT4, PIN2, (PFS_PSEL_SCI | R_PFS_PMR)}
#define GPIO_DE1_2                         (gpio_pinset_t){ PORT4, PIN3, (PFS_PSEL_SCI | R_PFS_PMR)}
#define GPIO_DE2_1                         (gpio_pinset_t){ PORT4, PIN5, (PFS_PSEL_SCI | R_PFS_PMR)}
#define GPIO_DE2_2                         (gpio_pinset_t){ PORT7, PIN1, (PFS_PSEL_SCI | R_PFS_PMR)}
#define GPIO_DE2_3                         (gpio_pinset_t){ PORT8, PIN3, (PFS_PSEL_SCI | R_PFS_PMR)}
#define GPIO_DE2_4                         (gpio_pinset_t){ PORT8, PIN4, (PFS_PSEL_SCI | R_PFS_PMR)}
#define GPIO_DE3_1                         (gpio_pinset_t){ PORT3, PIN11, (PFS_PSEL_SCI | R_PFS_PMR)}
#define GPIO_DE3_2                         (gpio_pinset_t){ PORT3, PIN12, (PFS_PSEL_SCI | R_PFS_PMR)}
#define GPIO_DE3_3                         (gpio_pinset_t){ PORT4, PIN10, (PFS_PSEL_SCI | R_PFS_PMR)}
#define GPIO_DE3_4                         (gpio_pinset_t){ PORT4, PIN11, (PFS_PSEL_SCI | R_PFS_PMR)}
#define GPIO_DE4_1                         (gpio_pinset_t){ PORT2, PIN4, (PFS_PSEL_SCI | R_PFS_PMR)}
#define GPIO_DE4_2                         (gpio_pinset_t){ PORT4, PIN7, (PFS_PSEL_SCI | R_PFS_PMR)}
#define GPIO_DE4_3                         (gpio_pinset_t){ PORT7, PIN8, (PFS_PSEL_SCI | R_PFS_PMR)}
#define GPIO_DE4_4                         (gpio_pinset_t){ PORT7, PIN9, (PFS_PSEL_SCI | R_PFS_PMR)}
#define GPIO_DE9_1                         (gpio_pinset_t){ PORT1, PIN0, (PFS_PSEL_SCI | R_PFS_PMR)}
#define GPIO_DE9_2                         (gpio_pinset_t){ PORT1, PIN3, (PFS_PSEL_SCI | R_PFS_PMR)}
#define GPIO_DE9_3                         (gpio_pinset_t){ PORT2, PIN10, (PFS_PSEL_SCI | R_PFS_PMR)}
#define GPIO_DE9_4                         (gpio_pinset_t){ PORT2, PIN11, (PFS_PSEL_SCI | R_PFS_PMR)}
#define GPIO_ET0_COL_1                         (gpio_pinset_t){ PORT6, PIN10, (PFS_PSEL_ETHERNET | R_PFS_PMR)}
#define GPIO_ET0_CRS_RMII0_CRS_DV_A_1                         (gpio_pinset_t){ PORT1, PIN12, (PFS_PSEL_ETHERNET | R_PFS_PMR)}
#define GPIO_ET0_CRS_RMII0_CRS_DV_B_1                         (gpio_pinset_t){ PORT7, PIN5, (PFS_PSEL_ETHERNET | R_PFS_PMR)}
#define GPIO_ET0_ERXD0_1                         (gpio_pinset_t){ PORT3, PIN1, (PFS_PSEL_SCI | R_PFS_PMR)}
#define GPIO_ET0_ERXD0_2                         (gpio_pinset_t){ PORT7, PIN3, (PFS_PSEL_SCI | R_PFS_PMR)}
#define GPIO_ET0_ERXD1_1                         (gpio_pinset_t){ PORT3, PIN2, (PFS_PSEL_SCI | R_PFS_PMR)}
#define GPIO_ET0_ERXD1_2                         (gpio_pinset_t){ PORT7, PIN2, (PFS_PSEL_SCI | R_PFS_PMR)}
#define GPIO_ET0_ERXD2_1                         (gpio_pinset_t){ PORT6, PIN11, (PFS_PSEL_SCI | R_PFS_PMR)}
#define GPIO_ET0_ERXD3_1                         (gpio_pinset_t){ PORT6, PIN12, (PFS_PSEL_SCI | R_PFS_PMR)}
#define GPIO_ET0_ETXD0_1                         (gpio_pinset_t){ PORT3, PIN3, (PFS_PSEL_SCI | R_PFS_PMR)}
#define GPIO_ET0_ETXD0_2                         (gpio_pinset_t){ PORT7, PIN1, (PFS_PSEL_SCI | R_PFS_PMR)}
#define GPIO_ET0_ETXD1_1                         (gpio_pinset_t){ PORT3, PIN4, (PFS_PSEL_SCI | R_PFS_PMR)}
#define GPIO_ET0_ETXD1_2                         (gpio_pinset_t){ PORT7, PIN0, (PFS_PSEL_SCI | R_PFS_PMR)}
#define GPIO_ET0_ETXD2_1                         (gpio_pinset_t){ PORT3, PIN10, (PFS_PSEL_SCI | R_PFS_PMR)}
#define GPIO_ET0_ETXD3_1                         (gpio_pinset_t){ PORT3, PIN9, (PFS_PSEL_SCI | R_PFS_PMR)}
#define GPIO_ET0_EXOUT_1                         (gpio_pinset_t){ PORT1, PIN13, (PFS_PSEL_ETHERNET | R_PFS_PMR)}
#define GPIO_ET0_EXOUT_2                         (gpio_pinset_t){ PORT4, PIN4, (PFS_PSEL_ETHERNET | R_PFS_PMR)}
#define GPIO_ET0_LINKSTA_1                         (gpio_pinset_t){ PORT1, PIN14, (PFS_PSEL_ETHERNET | R_PFS_PMR)}
#define GPIO_ET0_LINKSTA_2                         (gpio_pinset_t){ PORT4, PIN3, (PFS_PSEL_ETHERNET | R_PFS_PMR)}
#define GPIO_ET0_MDC_1                         (gpio_pinset_t){ PORT3, PIN8, (PFS_PSEL_ETHERNET | R_PFS_PMR)}
#define GPIO_ET0_MDC_2                         (gpio_pinset_t){ PORT4, PIN1, (PFS_PSEL_ETHERNET | R_PFS_PMR)}
#define GPIO_ET0_MDIO_1                         (gpio_pinset_t){ PORT3, PIN7, (PFS_PSEL_ETHERNET | R_PFS_PMR)}
#define GPIO_ET0_MDIO_2                         (gpio_pinset_t){ PORT4, PIN2, (PFS_PSEL_ETHERNET | R_PFS_PMR)}
#define GPIO_ET0_RX_CLK_RMII0_RX_ER_A_1                         (gpio_pinset_t){ PORT3, PIN0, (PFS_PSEL_ETHERNET | R_PFS_PMR)}
#define GPIO_ET0_RX_CLK_RMII0_RX_ER_B_1                         (gpio_pinset_t){ PORT7, PIN4, (PFS_PSEL_ETHERNET | R_PFS_PMR)}
#define GPIO_ET0_RX_DV_1                         (gpio_pinset_t){ PORT6, PIN9, (PFS_PSEL_ETHERNET | R_PFS_PMR)}
#define GPIO_ET0_RX_ER_1                         (gpio_pinset_t){ PORT3, PIN5, (PFS_PSEL_SCI | R_PFS_PMR)}
#define GPIO_ET0_RX_ER_2                         (gpio_pinset_t){ PORT4, PIN6, (PFS_PSEL_SCI | R_PFS_PMR)}
#define GPIO_ET0_TX_CLK_1                         (gpio_pinset_t){ PORT3, PIN12, (PFS_PSEL_ETHERNET | R_PFS_PMR)}
#define GPIO_ET0_TX_EN_1                         (gpio_pinset_t){ PORT3, PIN6, (PFS_PSEL_SCI | R_PFS_PMR)}
#define GPIO_ET0_TX_EN_2                         (gpio_pinset_t){ PORT4, PIN5, (PFS_PSEL_SCI | R_PFS_PMR)}
#define GPIO_ET0_TX_ER_1                         (gpio_pinset_t){ PORT3, PIN11, (PFS_PSEL_ETHERNET | R_PFS_PMR)}
#define GPIO_ET0_WOL_1                         (gpio_pinset_t){ PORT1, PIN15, (PFS_PSEL_ETHERNET | R_PFS_PMR)}
#define GPIO_ET0_WOL_2                         (gpio_pinset_t){ PORT4, PIN0, (PFS_PSEL_ETHERNET | R_PFS_PMR)}
#define GPIO_GTADSM0_1                         (gpio_pinset_t){ PORT3, PIN12, (PFS_PSEL_GPT | R_PFS_PMR)}
#define GPIO_GTADSM0_2                         (gpio_pinset_t){ PORT4, PIN15, (PFS_PSEL_GPT | R_PFS_PMR)}
#define GPIO_GTADSM0_3                         (gpio_pinset_t){ PORT7, PIN4, (PFS_PSEL_GPT | R_PFS_PMR)}
#define GPIO_GTADSM1_1                         (gpio_pinset_t){ PORT3, PIN11, (PFS_PSEL_GPT | R_PFS_PMR)}
#define GPIO_GTADSM1_2                         (gpio_pinset_t){ PORT4, PIN14, (PFS_PSEL_GPT | R_PFS_PMR)}
#define GPIO_GTADSM1_3                         (gpio_pinset_t){ PORT7, PIN5, (PFS_PSEL_GPT | R_PFS_PMR)}
#define GPIO_GTETRGA_1                         (gpio_pinset_t){ PORT1, PIN0, (PFS_PSEL_GPT | R_PFS_PMR)}
#define GPIO_GTETRGA_2                         (gpio_pinset_t){ PORT4, PIN1, (PFS_PSEL_GPT | R_PFS_PMR)}
#define GPIO_GTETRGA_3                         (gpio_pinset_t){ PORT6, PIN13, (PFS_PSEL_GPT | R_PFS_PMR)}
#define GPIO_GTETRGB_1                         (gpio_pinset_t){ PORT1, PIN1, (PFS_PSEL_GPT | R_PFS_PMR)}
#define GPIO_GTETRGB_2                         (gpio_pinset_t){ PORT1, PIN4, (PFS_PSEL_GPT | R_PFS_PMR)}
#define GPIO_GTETRGB_3                         (gpio_pinset_t){ PORT6, PIN14, (PFS_PSEL_GPT | R_PFS_PMR)}
#define GPIO_GTETRGC_1                         (gpio_pinset_t){ PORT2, PIN13, (PFS_PSEL_GPT | R_PFS_PMR)}
#define GPIO_GTETRGC_2                         (gpio_pinset_t){ PORT8, PIN3, (PFS_PSEL_GPT | R_PFS_PMR)}
#define GPIO_GTETRGD_1                         (gpio_pinset_t){ PORT2, PIN12, (PFS_PSEL_GPT | R_PFS_PMR)}
#define GPIO_GTETRGD_2                         (gpio_pinset_t){ PORT8, PIN4, (PFS_PSEL_GPT | R_PFS_PMR)}
#define GPIO_GTIOC0A_1                         (gpio_pinset_t){ PORT2, PIN11, (PFS_PSEL_GPT | R_PFS_PMR)}
#define GPIO_GTIOC0A_2                         (gpio_pinset_t){ PORT2, PIN13, (PFS_PSEL_GPT | R_PFS_PMR)}
#define GPIO_GTIOC0A_3                         (gpio_pinset_t){ PORT4, PIN15, (PFS_PSEL_GPT | R_PFS_PMR)}
#define GPIO_GTIOC0A_4                         (gpio_pinset_t){ PORT5, PIN12, (PFS_PSEL_GPT | R_PFS_PMR)}
#define GPIO_GTIOC0B_1                         (gpio_pinset_t){ PORT2, PIN10, (PFS_PSEL_GPT | R_PFS_PMR)}
#define GPIO_GTIOC0B_2                         (gpio_pinset_t){ PORT2, PIN12, (PFS_PSEL_GPT | R_PFS_PMR)}
#define GPIO_GTIOC0B_3                         (gpio_pinset_t){ PORT4, PIN14, (PFS_PSEL_GPT | R_PFS_PMR)}
#define GPIO_GTIOC0B_4                         (gpio_pinset_t){ PORT5, PIN11, (PFS_PSEL_GPT | R_PFS_PMR)}
#define GPIO_GTIOC10A_1                         (gpio_pinset_t){ PORT4, PIN8, (PFS_PSEL_GPT | R_PFS_PMR)}
#define GPIO_GTIOC10B_1                         (gpio_pinset_t){ PORT4, PIN7, (PFS_PSEL_GPT | R_PFS_PMR)}
#define GPIO_GTIOC11A_1                         (gpio_pinset_t){ PORT8, PIN0, (PFS_PSEL_GPT | R_PFS_PMR)}
#define GPIO_GTIOC11B_1                         (gpio_pinset_t){ PORT8, PIN1, (PFS_PSEL_GPT | R_PFS_PMR)}
#define GPIO_GTIOC12A_1                         (gpio_pinset_t){ PORT8, PIN2, (PFS_PSEL_GPT | R_PFS_PMR)}
#define GPIO_GTIOC12B_1                         (gpio_pinset_t){ PORT8, PIN3, (PFS_PSEL_GPT | R_PFS_PMR)}
#define GPIO_GTIOC13A_1                         (gpio_pinset_t){ PORT8, PIN4, (PFS_PSEL_GPT | R_PFS_PMR)}
#define GPIO_GTIOC13B_1                         (gpio_pinset_t){ PORT8, PIN8, (PFS_PSEL_GPT | R_PFS_PMR)}
#define GPIO_GTIOC1A_1                         (gpio_pinset_t){ PORT1, PIN5, (PFS_PSEL_GPT | R_PFS_PMR)}
#define GPIO_GTIOC1A_2                         (gpio_pinset_t){ PORT2, PIN9, (PFS_PSEL_GPT | R_PFS_PMR)}
#define GPIO_GTIOC1A_3                         (gpio_pinset_t){ PORT4, PIN5, (PFS_PSEL_GPT | R_PFS_PMR)}
#define GPIO_GTIOC1B_1                         (gpio_pinset_t){ PORT1, PIN4, (PFS_PSEL_GPT | R_PFS_PMR)}
#define GPIO_GTIOC1B_2                         (gpio_pinset_t){ PORT2, PIN8, (PFS_PSEL_GPT | R_PFS_PMR)}
#define GPIO_GTIOC1B_3                         (gpio_pinset_t){ PORT4, PIN6, (PFS_PSEL_GPT | R_PFS_PMR)}
#define GPIO_GTIOC2A_1                         (gpio_pinset_t){ PORT1, PIN3, (PFS_PSEL_GPT | R_PFS_PMR)}
#define GPIO_GTIOC2A_2                         (gpio_pinset_t){ PORT1, PIN13, (PFS_PSEL_GPT | R_PFS_PMR)}
#define GPIO_GTIOC2A_3                         (gpio_pinset_t){ PORT7, PIN13, (PFS_PSEL_GPT | R_PFS_PMR)}
#define GPIO_GTIOC2B_1                         (gpio_pinset_t){ PORT1, PIN2, (PFS_PSEL_GPT | R_PFS_PMR)}
#define GPIO_GTIOC2B_2                         (gpio_pinset_t){ PORT1, PIN14, (PFS_PSEL_GPT | R_PFS_PMR)}
#define GPIO_GTIOC2B_3                         (gpio_pinset_t){ PORT7, PIN12, (PFS_PSEL_GPT | R_PFS_PMR)}
#define GPIO_GTIOC3A_1                         (gpio_pinset_t){ PORT3, PIN0, (PFS_PSEL_GPT | R_PFS_PMR)}
#define GPIO_GTIOC3A_2                         (gpio_pinset_t){ PORT4, PIN3, (PFS_PSEL_GPT | R_PFS_PMR)}
#define GPIO_GTIOC3B_1                         (gpio_pinset_t){ PORT1, PIN12, (PFS_PSEL_GPT | R_PFS_PMR)}
#define GPIO_GTIOC3B_2                         (gpio_pinset_t){ PORT4, PIN4, (PFS_PSEL_GPT | R_PFS_PMR)}
#define GPIO_GTIOC4A_1                         (gpio_pinset_t){ PORT2, PIN5, (PFS_PSEL_GPT | R_PFS_PMR)}
#define GPIO_GTIOC4A_2                         (gpio_pinset_t){ PORT3, PIN2, (PFS_PSEL_GPT | R_PFS_PMR)}
#define GPIO_GTIOC4A_3                         (gpio_pinset_t){ PORT6, PIN10, (PFS_PSEL_GPT | R_PFS_PMR)}
#define GPIO_GTIOC4B_1                         (gpio_pinset_t){ PORT2, PIN4, (PFS_PSEL_GPT | R_PFS_PMR)}
#define GPIO_GTIOC4B_2                         (gpio_pinset_t){ PORT3, PIN1, (PFS_PSEL_GPT | R_PFS_PMR)}
#define GPIO_GTIOC4B_3                         (gpio_pinset_t){ PORT6, PIN11, (PFS_PSEL_GPT | R_PFS_PMR)}
#define GPIO_GTIOC5A_1                         (gpio_pinset_t){ PORT1, PIN15, (PFS_PSEL_GPT | R_PFS_PMR)}
#define GPIO_GTIOC5A_2                         (gpio_pinset_t){ PORT2, PIN3, (PFS_PSEL_GPT | R_PFS_PMR)}
#define GPIO_GTIOC5A_3                         (gpio_pinset_t){ PORT7, PIN0, (PFS_PSEL_GPT | R_PFS_PMR)}
#define GPIO_GTIOC5B_1                         (gpio_pinset_t){ PORT2, PIN2, (PFS_PSEL_GPT | R_PFS_PMR)}
#define GPIO_GTIOC5B_2                         (gpio_pinset_t){ PORT6, PIN9, (PFS_PSEL_GPT | R_PFS_PMR)}
#define GPIO_GTIOC5B_3                         (gpio_pinset_t){ PORT7, PIN1, (PFS_PSEL_GPT | R_PFS_PMR)}
#define GPIO_IVCMP0_1                         (gpio_pinset_t){ PORT5, PIN13, (PFS_PSEL_OPAMP | R_PFS_PMR)}
#define GPIO_MISOA_A_1                         (gpio_pinset_t){ PORT3, PIN13, (PFS_PSEL_SPI | R_PFS_PMR)}
#define GPIO_MISOA_B_1                         (gpio_pinset_t){ PORT6, PIN9, (PFS_PSEL_SPI | R_PFS_PMR)}
#define GPIO_MISOA_C_1                         (gpio_pinset_t){ PORT7, PIN0, (PFS_PSEL_SPI | R_PFS_PMR)}
#define GPIO_MISOB_A_1                         (gpio_pinset_t){ PORT1, PIN0, (PFS_PSEL_SPI | R_PFS_PMR)}
#define GPIO_MISOB_B_1                         (gpio_pinset_t){ PORT4, PIN10, (PFS_PSEL_SPI | R_PFS_PMR)}
#define GPIO_MOSIA_A_1                         (gpio_pinset_t){ PORT2, PIN2, (PFS_PSEL_SPI | R_PFS_PMR)}
#define GPIO_MOSIA_B_1                         (gpio_pinset_t){ PORT1, PIN15, (PFS_PSEL_SPI | R_PFS_PMR)}
#define GPIO_MOSIA_B_2                         (gpio_pinset_t){ PORT6, PIN11, (PFS_PSEL_SPI | R_PFS_PMR)}
#define GPIO_MOSIA_C_1                         (gpio_pinset_t){ PORT7, PIN1, (PFS_PSEL_SPI | R_PFS_PMR)}
#define GPIO_MOSIB_A_1                         (gpio_pinset_t){ PORT1, PIN1, (PFS_PSEL_SPI | R_PFS_PMR)}
#define GPIO_MOSIB_B_1                         (gpio_pinset_t){ PORT4, PIN11, (PFS_PSEL_SPI | R_PFS_PMR)}
#define GPIO_OM_CS0_1                         (gpio_pinset_t){ PORT1, PIN7, (PFS_PSEL_XSPI | R_PFS_PMR)}
#define GPIO_OM_CS1_1                         (gpio_pinset_t){ PORT1, PIN4, (PFS_PSEL_XSPI | R_PFS_PMR)}
#define GPIO_OM_DQS_1                         (gpio_pinset_t){ PORT8, PIN1, (PFS_PSEL_XSPI | R_PFS_PMR)}
#define GPIO_OM_ECSINT1_1                         (gpio_pinset_t){ PORT1, PIN5, (PFS_PSEL_XSPI | R_PFS_PMR)}
#define GPIO_OM_RESET_1                         (gpio_pinset_t){ PORT1, PIN6, (PFS_PSEL_XSPI | R_PFS_PMR)}
#define GPIO_OM_RSTO1_1                         (gpio_pinset_t){ PORT6, PIN0, (PFS_PSEL_XSPI | R_PFS_PMR)}
#define GPIO_OM_SCLKN_1                         (gpio_pinset_t){ PORT8, PIN9, (PFS_PSEL_IIC | R_PFS_PMR)}
#define GPIO_OM_SCLK_1                         (gpio_pinset_t){ PORT8, PIN8, (PFS_PSEL_IIC | R_PFS_PMR)}
#define GPIO_OM_SIO0_1                         (gpio_pinset_t){ PORT1, PIN0, (PFS_PSEL_XSPI | R_PFS_PMR)}
#define GPIO_OM_SIO1_1                         (gpio_pinset_t){ PORT8, PIN3, (PFS_PSEL_XSPI | R_PFS_PMR)}
#define GPIO_OM_SIO2_1                         (gpio_pinset_t){ PORT1, PIN3, (PFS_PSEL_XSPI | R_PFS_PMR)}
#define GPIO_OM_SIO3_1                         (gpio_pinset_t){ PORT1, PIN1, (PFS_PSEL_XSPI | R_PFS_PMR)}
#define GPIO_OM_SIO4_1                         (gpio_pinset_t){ PORT1, PIN2, (PFS_PSEL_XSPI | R_PFS_PMR)}
#define GPIO_OM_SIO5_1                         (gpio_pinset_t){ PORT8, PIN0, (PFS_PSEL_XSPI | R_PFS_PMR)}
#define GPIO_OM_SIO6_1                         (gpio_pinset_t){ PORT8, PIN2, (PFS_PSEL_XSPI | R_PFS_PMR)}
#define GPIO_OM_SIO7_1                         (gpio_pinset_t){ PORT8, PIN4, (PFS_PSEL_XSPI | R_PFS_PMR)}
#define GPIO_OM_WP1_1                         (gpio_pinset_t){ PORT6, PIN1, (PFS_PSEL_XSPI | R_PFS_PMR)}
#define GPIO_RSPCKA_A_1                         (gpio_pinset_t){ PORT2, PIN3, (PFS_PSEL_SPI | R_PFS_PMR)}
#define GPIO_RSPCKA_B_1                         (gpio_pinset_t){ PORT6, PIN10, (PFS_PSEL_SPI | R_PFS_PMR)}
#define GPIO_RSPCKA_C_1                         (gpio_pinset_t){ PORT7, PIN2, (PFS_PSEL_SPI | R_PFS_PMR)}
#define GPIO_RSPCKB_A_1                         (gpio_pinset_t){ PORT1, PIN2, (PFS_PSEL_SPI | R_PFS_PMR)}
#define GPIO_RSPCKB_B_1                         (gpio_pinset_t){ PORT4, PIN12, (PFS_PSEL_SPI | R_PFS_PMR)}
#define GPIO_RTCIC0_1                         (gpio_pinset_t){ PORT4, PIN2, (PFS_PSEL_CLKOUT_ACMPLP_RTC | R_PFS_PMR)}
#define GPIO_RTCIC1_1                         (gpio_pinset_t){ PORT4, PIN3, (PFS_PSEL_CLKOUT_ACMPLP_RTC | R_PFS_PMR)}
#define GPIO_RTCIC2_1                         (gpio_pinset_t){ PORT4, PIN4, (PFS_PSEL_CLKOUT_ACMPLP_RTC | R_PFS_PMR)}
#define GPIO_RTCOUT_1                         (gpio_pinset_t){ PORT4, PIN7, (PFS_PSEL_CLKOUT_ACMPLP_RTC | R_PFS_PMR)}
#define GPIO_RTCOUT_2                         (gpio_pinset_t){ PORT6, PIN1, (PFS_PSEL_CLKOUT_ACMPLP_RTC | R_PFS_PMR)}
#define GPIO_RXD0_MISO0_SCL0_A                         (gpio_pinset_t){ PORT1, PIN13, (PFS_PSEL_SCI | R_PFS_PMR)}
#define GPIO_RXD0_MISO0_SCL0_B                         (gpio_pinset_t){ PORT6, PIN2, (PFS_PSEL_SCI | R_PFS_PMR)}
#define GPIO_RXD0_MISO0_SCL0_C                         (gpio_pinset_t){ PORT6, PIN10, (PFS_PSEL_SCI | R_PFS_PMR)}
#define GPIO_RXD1_MISO1_SCL1_A                         (gpio_pinset_t){ PORT4, PIN1, (PFS_PSEL_SCI | R_PFS_PMR)}
#define GPIO_RXD1_MISO1_SCL1_C                         (gpio_pinset_t){ PORT2, PIN12, (PFS_PSEL_SCI | R_PFS_PMR)}
#define GPIO_RXD2_MISO2_SCL2_A                         (gpio_pinset_t){ PORT8, PIN2, (PFS_PSEL_SCI | R_PFS_PMR)}
#define GPIO_RXD2_MISO2_SCL2_B                         (gpio_pinset_t){ PORT7, PIN0, (PFS_PSEL_SCI | R_PFS_PMR)}
#define GPIO_RXD3_MISO3_SCL3_A                         (gpio_pinset_t){ PORT4, PIN8, (PFS_PSEL_SCI | R_PFS_PMR)}
#define GPIO_RXD3_MISO3_SCL3_B                         (gpio_pinset_t){ PORT3, PIN9, (PFS_PSEL_SCI | R_PFS_PMR)}
#define GPIO_RXD4_MISO4_SCL4_A                         (gpio_pinset_t){ PORT2, PIN6, (PFS_PSEL_SCI | R_PFS_PMR)}
#define GPIO_RXD4_MISO4_SCL4_B                         (gpio_pinset_t){ PORT4, PIN14, (PFS_PSEL_SCI | R_PFS_PMR)}
#define GPIO_RXD9_MISO9_SCL9_A                         (gpio_pinset_t){ PORT1, PIN1, (PFS_PSEL_SCI | R_PFS_PMR)}
#define GPIO_RXD9_MISO9_SCL9_B                         (gpio_pinset_t){ PORT2, PIN8, (PFS_PSEL_SCI | R_PFS_PMR)}
#define GPIO_SCK0_A_1                         (gpio_pinset_t){ PORT3, PIN0, (PFS_PSEL_SCI | R_PFS_PMR)}
#define GPIO_SCK0_B_1                         (gpio_pinset_t){ PORT6, PIN1, (PFS_PSEL_SCI | R_PFS_PMR)}
#define GPIO_SCK0_C_1                         (gpio_pinset_t){ PORT6, PIN11, (PFS_PSEL_SCI | R_PFS_PMR)}
#define GPIO_SCK1_A_1                         (gpio_pinset_t){ PORT4, PIN2, (PFS_PSEL_SCI | R_PFS_PMR)}
#define GPIO_SCK2_A_1                         (gpio_pinset_t){ PORT8, PIN3, (PFS_PSEL_SCI | R_PFS_PMR)}
#define GPIO_SCK2_B_1                         (gpio_pinset_t){ PORT4, PIN5, (PFS_PSEL_SCI | R_PFS_PMR)}
#define GPIO_SCK3_A_1                         (gpio_pinset_t){ PORT4, PIN10, (PFS_PSEL_SCI | R_PFS_PMR)}
#define GPIO_SCK3_B_1                         (gpio_pinset_t){ PORT3, PIN11, (PFS_PSEL_SCI | R_PFS_PMR)}
#define GPIO_SCK4_A_1                         (gpio_pinset_t){ PORT2, PIN4, (PFS_PSEL_SCI | R_PFS_PMR)}
#define GPIO_SCK4_B_1                         (gpio_pinset_t){ PORT7, PIN8, (PFS_PSEL_SCI | R_PFS_PMR)}
#define GPIO_SCK9_A_1                         (gpio_pinset_t){ PORT1, PIN0, (PFS_PSEL_SCI | R_PFS_PMR)}
#define GPIO_SCK9_B_1                         (gpio_pinset_t){ PORT2, PIN11, (PFS_PSEL_SCI | R_PFS_PMR)}
#define GPIO_SCL0_A_1                         (gpio_pinset_t){ PORT4, PIN10, (PFS_PSEL_IIC | R_PFS_PMR)}
#define GPIO_SCL0_B_1                         (gpio_pinset_t){ PORT4, PIN8, (PFS_PSEL_IIC | R_PFS_PMR)}
#define GPIO_SCL1_A_1                         (gpio_pinset_t){ PORT5, PIN12, (PFS_PSEL_IIC | R_PFS_PMR)}
#define GPIO_SCL1_B_1                         (gpio_pinset_t){ PORT2, PIN5, (PFS_PSEL_IIC | R_PFS_PMR)}
#define GPIO_SDA0_A_1                         (gpio_pinset_t){ PORT4, PIN9, (PFS_PSEL_IIC | R_PFS_PMR)}
#define GPIO_SDA0_B_1                         (gpio_pinset_t){ PORT4, PIN7, (PFS_PSEL_IIC | R_PFS_PMR)}
#define GPIO_SDA1_A_1                         (gpio_pinset_t){ PORT5, PIN11, (PFS_PSEL_IIC | R_PFS_PMR)}
#define GPIO_SDA1_B_1                         (gpio_pinset_t){ PORT2, PIN6, (PFS_PSEL_IIC | R_PFS_PMR)}
#define GPIO_SSIBCK0_A_1                         (gpio_pinset_t){ PORT4, PIN3, (PFS_PSEL_SSIE | R_PFS_PMR)}
#define GPIO_SSIBCK0_B_1                         (gpio_pinset_t){ PORT1, PIN12, (PFS_PSEL_SSIE | R_PFS_PMR)}
#define GPIO_SSIBCK1_A_1                         (gpio_pinset_t){ PORT2, PIN4, (PFS_PSEL_SSIE | R_PFS_PMR)}
#define GPIO_SSIBCK1_B_1                         (gpio_pinset_t){ PORT7, PIN2, (PFS_PSEL_SSIE | R_PFS_PMR)}
#define GPIO_SSIDATA1_A_1                         (gpio_pinset_t){ PORT2, PIN6, (PFS_PSEL_SSIE | R_PFS_PMR)}
#define GPIO_SSIDATA1_B_1                         (gpio_pinset_t){ PORT7, PIN0, (PFS_PSEL_SSIE | R_PFS_PMR)}
#define GPIO_SSILRCK0_SSIFS0_A_1                         (gpio_pinset_t){ PORT4, PIN4, (PFS_PSEL_SSIE | R_PFS_PMR)}
#define GPIO_SSILRCK0_SSIFS0_B_1                         (gpio_pinset_t){ PORT1, PIN13, (PFS_PSEL_SSIE | R_PFS_PMR)}
#define GPIO_SSILRCK1_SSIFS1_A_1                         (gpio_pinset_t){ PORT2, PIN5, (PFS_PSEL_SSIE | R_PFS_PMR)}
#define GPIO_SSILRCK1_SSIFS1_B_1                         (gpio_pinset_t){ PORT7, PIN1, (PFS_PSEL_SSIE | R_PFS_PMR)}
#define GPIO_SSIRXD0_A                         (gpio_pinset_t){ PORT4, PIN6, (PFS_PSEL_SCI | R_PFS_PMR)}
#define GPIO_SSIRXD0_B                         (gpio_pinset_t){ PORT1, PIN14, (PFS_PSEL_SCI | R_PFS_PMR)}
#define GPIO_SSITXD0_A                         (gpio_pinset_t){ PORT4, PIN5, (PFS_PSEL_SCI | R_PFS_PMR)}
#define GPIO_SSITXD0_B                         (gpio_pinset_t){ PORT1, PIN15, (PFS_PSEL_SCI | R_PFS_PMR)}
#define GPIO_SSLA0_A_1                         (gpio_pinset_t){ PORT2, PIN4, (PFS_PSEL_SPI | R_PFS_PMR)}
#define GPIO_SSLA0_B_1                         (gpio_pinset_t){ PORT1, PIN14, (PFS_PSEL_SPI | R_PFS_PMR)}
#define GPIO_SSLA0_B_2                         (gpio_pinset_t){ PORT6, PIN12, (PFS_PSEL_SPI | R_PFS_PMR)}
#define GPIO_SSLA0_C_1                         (gpio_pinset_t){ PORT7, PIN3, (PFS_PSEL_SPI | R_PFS_PMR)}
#define GPIO_SSLA1_A_1                         (gpio_pinset_t){ PORT2, PIN5, (PFS_PSEL_SPI | R_PFS_PMR)}
#define GPIO_SSLA1_B_1                         (gpio_pinset_t){ PORT1, PIN13, (PFS_PSEL_SPI | R_PFS_PMR)}
#define GPIO_SSLA1_C_1                         (gpio_pinset_t){ PORT7, PIN4, (PFS_PSEL_SPI | R_PFS_PMR)}
#define GPIO_SSLA2_A_1                         (gpio_pinset_t){ PORT2, PIN6, (PFS_PSEL_SPI | R_PFS_PMR)}
#define GPIO_SSLA2_B_1                         (gpio_pinset_t){ PORT1, PIN12, (PFS_PSEL_SPI | R_PFS_PMR)}
#define GPIO_SSLA2_C_1                         (gpio_pinset_t){ PORT7, PIN5, (PFS_PSEL_SPI | R_PFS_PMR)}
#define GPIO_SSLA3_A_1                         (gpio_pinset_t){ PORT4, PIN7, (PFS_PSEL_SPI | R_PFS_PMR)}
#define GPIO_SSLA3_B_1                         (gpio_pinset_t){ PORT3, PIN0, (PFS_PSEL_SPI | R_PFS_PMR)}
#define GPIO_SSLA3_C_1                         (gpio_pinset_t){ PORT4, PIN6, (PFS_PSEL_SPI | R_PFS_PMR)}
#define GPIO_SSLB0_A_1                         (gpio_pinset_t){ PORT1, PIN3, (PFS_PSEL_SPI | R_PFS_PMR)}
#define GPIO_SSLB0_B_1                         (gpio_pinset_t){ PORT4, PIN13, (PFS_PSEL_SPI | R_PFS_PMR)}
#define GPIO_SSLB1_A_1                         (gpio_pinset_t){ PORT1, PIN4, (PFS_PSEL_SPI | R_PFS_PMR)}
#define GPIO_SSLB1_B_1                         (gpio_pinset_t){ PORT4, PIN14, (PFS_PSEL_SPI | R_PFS_PMR)}
#define GPIO_SSLB2_A_1                         (gpio_pinset_t){ PORT1, PIN5, (PFS_PSEL_SPI | R_PFS_PMR)}
#define GPIO_SSLB2_B_1                         (gpio_pinset_t){ PORT4, PIN15, (PFS_PSEL_SPI | R_PFS_PMR)}
#define GPIO_SSLB3_A_1                         (gpio_pinset_t){ PORT1, PIN6, (PFS_PSEL_SPI | R_PFS_PMR)}
#define GPIO_SSLB3_B_1                         (gpio_pinset_t){ PORT7, PIN8, (PFS_PSEL_SPI | R_PFS_PMR)}
#define GPIO_TXD0_MOSI0_SDA0_A                         (gpio_pinset_t){ PORT1, PIN12, (PFS_PSEL_SCI | R_PFS_PMR)}
#define GPIO_TXD0_MOSI0_SDA0_B                         (gpio_pinset_t){ PORT6, PIN3, (PFS_PSEL_SCI | R_PFS_PMR)}
#define GPIO_TXD0_MOSI0_SDA0_C                         (gpio_pinset_t){ PORT6, PIN9, (PFS_PSEL_SCI | R_PFS_PMR)}
#define GPIO_TXD1_MOSI1_SDA1_A                         (gpio_pinset_t){ PORT4, PIN0, (PFS_PSEL_SCI | R_PFS_PMR)}
#define GPIO_TXD1_MOSI1_SDA1_C                         (gpio_pinset_t){ PORT2, PIN13, (PFS_PSEL_SCI | R_PFS_PMR)}
#define GPIO_TXD2_MOSI2_SDA2_A                         (gpio_pinset_t){ PORT8, PIN1, (PFS_PSEL_SCI | R_PFS_PMR)}
#define GPIO_TXD2_MOSI2_SDA2_B                         (gpio_pinset_t){ PORT4, PIN6, (PFS_PSEL_SCI | R_PFS_PMR)}
#define GPIO_TXD3_MOSI3_SDA3_A                         (gpio_pinset_t){ PORT4, PIN9, (PFS_PSEL_SCI | R_PFS_PMR)}
#define GPIO_TXD3_MOSI3_SDA3_B                         (gpio_pinset_t){ PORT3, PIN10, (PFS_PSEL_SCI | R_PFS_PMR)}
#define GPIO_TXD4_MOSI4_SDA4_A                         (gpio_pinset_t){ PORT2, PIN5, (PFS_PSEL_SCI | R_PFS_PMR)}
#define GPIO_TXD4_MOSI4_SDA4_B                         (gpio_pinset_t){ PORT4, PIN15, (PFS_PSEL_SCI | R_PFS_PMR)}
#define GPIO_TXD9_MOSI9_SDA9_A                         (gpio_pinset_t){ PORT1, PIN2, (PFS_PSEL_SCI | R_PFS_PMR)}
#define GPIO_TXD9_MOSI9_SDA9_B                         (gpio_pinset_t){ PORT2, PIN9, (PFS_PSEL_SCI | R_PFS_PMR)}
#define GPIO_ULPTEE0_1                         (gpio_pinset_t){ PORT2, PIN13, (PFS_PSEL_ULPT | R_PFS_PMR)}
#define GPIO_ULPTEE0_2                         (gpio_pinset_t){ PORT6, PIN2, (PFS_PSEL_ULPT | R_PFS_PMR)}
#define GPIO_ULPTEE0_DS_1                         (gpio_pinset_t){ PORT3, PIN1, (PFS_PSEL_ULPT | R_PFS_PMR)}
#define GPIO_ULPTEE1_1                         (gpio_pinset_t){ PORT3, PIN5, (PFS_PSEL_ULPT | R_PFS_PMR)}
#define GPIO_ULPTEE1_2                         (gpio_pinset_t){ PORT4, PIN13, (PFS_PSEL_ULPT | R_PFS_PMR)}
#define GPIO_ULPTEE1_DS_1                         (gpio_pinset_t){ PORT1, PIN6, (PFS_PSEL_ULPT | R_PFS_PMR)}
#define GPIO_ULPTEVI0_1                         (gpio_pinset_t){ PORT6, PIN1, (PFS_PSEL_ULPT | R_PFS_PMR)}
#define GPIO_ULPTEVI0_DS_1                         (gpio_pinset_t){ PORT3, PIN0, (PFS_PSEL_ULPT | R_PFS_PMR)}
#define GPIO_ULPTEVI1_1                         (gpio_pinset_t){ PORT3, PIN6, (PFS_PSEL_ULPT | R_PFS_PMR)}
#define GPIO_ULPTEVI1_DS_1                         (gpio_pinset_t){ PORT6, PIN0, (PFS_PSEL_ULPT | R_PFS_PMR)}
#define GPIO_ULPTO0_1                         (gpio_pinset_t){ PORT6, PIN3, (PFS_PSEL_ULPT | R_PFS_PMR)}
#define GPIO_ULPTO0_2                         (gpio_pinset_t){ PORT7, PIN2, (PFS_PSEL_ULPT | R_PFS_PMR)}
#define GPIO_ULPTO0_DS_1                         (gpio_pinset_t){ PORT3, PIN2, (PFS_PSEL_ULPT | R_PFS_PMR)}
#define GPIO_ULPTO1_1                         (gpio_pinset_t){ PORT3, PIN4, (PFS_PSEL_ULPT | R_PFS_PMR)}
#define GPIO_ULPTO1_2                         (gpio_pinset_t){ PORT7, PIN1, (PFS_PSEL_ULPT | R_PFS_PMR)}
#define GPIO_ULPTO1_DS_1                         (gpio_pinset_t){ PORT1, PIN5, (PFS_PSEL_ULPT | R_PFS_PMR)}
#define GPIO_ULPTOA0_1                         (gpio_pinset_t){ PORT4, PIN9, (PFS_PSEL_ULPT | R_PFS_PMR)}
#define GPIO_ULPTOA0_DS_1                         (gpio_pinset_t){ PORT1, PIN13, (PFS_PSEL_ULPT | R_PFS_PMR)}
#define GPIO_ULPTOA1_1                         (gpio_pinset_t){ PORT2, PIN3, (PFS_PSEL_ULPT | R_PFS_PMR)}
#define GPIO_ULPTOA1_2                         (gpio_pinset_t){ PORT3, PIN7, (PFS_PSEL_ULPT | R_PFS_PMR)}
#define GPIO_ULPTOA1_DS_1                         (gpio_pinset_t){ PORT6, PIN9, (PFS_PSEL_ULPT | R_PFS_PMR)}
#define GPIO_ULPTOB0_1                         (gpio_pinset_t){ PORT4, PIN8, (PFS_PSEL_ULPT | R_PFS_PMR)}
#define GPIO_ULPTOB0_DS_1                         (gpio_pinset_t){ PORT1, PIN12, (PFS_PSEL_ULPT | R_PFS_PMR)}
#define GPIO_ULPTOB1_1                         (gpio_pinset_t){ PORT2, PIN2, (PFS_PSEL_ULPT | R_PFS_PMR)}
#define GPIO_ULPTOB1_2                         (gpio_pinset_t){ PORT3, PIN8, (PFS_PSEL_ULPT | R_PFS_PMR)}
#define GPIO_ULPTOB1_DS_1                         (gpio_pinset_t){ PORT6, PIN10, (PFS_PSEL_ULPT | R_PFS_PMR)}
#define GPIO_USB_DM_1                         (gpio_pinset_t){ PORT8, PIN15, (PFS_PSEL_USBFS | R_PFS_PMR)}
#define GPIO_USB_DP_1                         (gpio_pinset_t){ PORT8, PIN14, (PFS_PSEL_USBFS | R_PFS_PMR)}
#define GPIO_USB_EXICEN_1                         (gpio_pinset_t){ PORT4, PIN12, (PFS_PSEL_USBFS | R_PFS_PMR)}
#define GPIO_USB_ID_1                         (gpio_pinset_t){ PORT4, PIN11, (PFS_PSEL_USBFS | R_PFS_PMR)}
#define GPIO_USB_OVRCURA_1                         (gpio_pinset_t){ PORT2, PIN5, (PFS_PSEL_USBFS | R_PFS_PMR)}
#define GPIO_USB_OVRCURA_DS_1                         (gpio_pinset_t){ PORT4, PIN9, (PFS_PSEL_USBFS | R_PFS_PMR)}
#define GPIO_USB_OVRCURB_1                         (gpio_pinset_t){ PORT2, PIN4, (PFS_PSEL_USBFS | R_PFS_PMR)}
#define GPIO_USB_OVRCURB_DS_1                         (gpio_pinset_t){ PORT4, PIN10, (PFS_PSEL_USBFS | R_PFS_PMR)}
#define GPIO_USB_VBUSEN_1                         (gpio_pinset_t){ PORT2, PIN6, (PFS_PSEL_USBFS | R_PFS_PMR)}
#define GPIO_USB_VBUSEN_2                         (gpio_pinset_t){ PORT4, PIN8, (PFS_PSEL_USBFS | R_PFS_PMR)}
#define GPIO_USB_VBUS_1                         (gpio_pinset_t){ PORT4, PIN7, (PFS_PSEL_USBFS | R_PFS_PMR)}
#define GPIO_VCOUT_1                         (gpio_pinset_t){ PORT2, PIN8, (PFS_PSEL_OPAMP | R_PFS_PMR)}
#define GPIO_VCOUT_2                         (gpio_pinset_t){ PORT7, PIN3, (PFS_PSEL_OPAMP | R_PFS_PMR)}
#define GPIO_VIO_CLK_1                         (gpio_pinset_t){ PORT7, PIN8, (PFS_PSEL_CEU | R_PFS_PMR)}
#define GPIO_VIO_D0_1                         (gpio_pinset_t){ PORT4, PIN0, (PFS_PSEL_CEU | R_PFS_PMR)}
#define GPIO_VIO_D1_1                         (gpio_pinset_t){ PORT4, PIN1, (PFS_PSEL_CEU | R_PFS_PMR)}
#define GPIO_VIO_D2_1                         (gpio_pinset_t){ PORT4, PIN5, (PFS_PSEL_CEU | R_PFS_PMR)}
#define GPIO_VIO_D3_1                         (gpio_pinset_t){ PORT4, PIN4, (PFS_PSEL_CEU | R_PFS_PMR)}
#define GPIO_VIO_D3_2                         (gpio_pinset_t){ PORT4, PIN6, (PFS_PSEL_CEU | R_PFS_PMR)}
#define GPIO_VIO_D4_1                         (gpio_pinset_t){ PORT7, PIN0, (PFS_PSEL_CEU | R_PFS_PMR)}
#define GPIO_VIO_D5_1                         (gpio_pinset_t){ PORT7, PIN1, (PFS_PSEL_CEU | R_PFS_PMR)}
#define GPIO_VIO_D6_1                         (gpio_pinset_t){ PORT7, PIN2, (PFS_PSEL_CEU | R_PFS_PMR)}
#define GPIO_VIO_D7_1                         (gpio_pinset_t){ PORT7, PIN3, (PFS_PSEL_CEU | R_PFS_PMR)}
#define GPIO_VIO_FLD_1                         (gpio_pinset_t){ PORT5, PIN13, (PFS_PSEL_CEU | R_PFS_PMR)}
#define GPIO_VIO_HD_1                         (gpio_pinset_t){ PORT7, PIN9, (PFS_PSEL_CEU | R_PFS_PMR)}
#define GPIO_VIO_VD_1                         (gpio_pinset_t){ PORT7, PIN10, (PFS_PSEL_CEU | R_PFS_PMR)}

/* External Interrupt Pin Definitions */
#define GPIO_IRQ0_P105                      (gpio_pinset_t){ PORT1, PIN5, (GPIO_INPUT | R_PFS_PCR | R_PFS_ISEL)}
#define GPIO_IRQ0_P206_DS                      (gpio_pinset_t){ PORT2, PIN6, (GPIO_INPUT | R_PFS_PCR | R_PFS_ISEL)}
#define GPIO_IRQ0_P400                      (gpio_pinset_t){ PORT4, PIN0, (GPIO_INPUT | R_PFS_PCR | R_PFS_ISEL)}
#define GPIO_IRQ0_P806                      (gpio_pinset_t){ PORT8, PIN6, (GPIO_INPUT | R_PFS_PCR | R_PFS_ISEL)}
#define GPIO_IRQ10_P005_DS                      (gpio_pinset_t){ PORT0, PIN5, (GPIO_INPUT | R_PFS_PCR | R_PFS_ISEL)}
#define GPIO_IRQ10_P709                      (gpio_pinset_t){ PORT7, PIN9, (GPIO_INPUT | R_PFS_PCR | R_PFS_ISEL)}
#define GPIO_IRQ11_P006_DS                      (gpio_pinset_t){ PORT0, PIN6, (GPIO_INPUT | R_PFS_PCR | R_PFS_ISEL)}
#define GPIO_IRQ11_P708                      (gpio_pinset_t){ PORT7, PIN8, (GPIO_INPUT | R_PFS_PCR | R_PFS_ISEL)}
#define GPIO_IRQ11_P800                      (gpio_pinset_t){ PORT8, PIN0, (GPIO_INPUT | R_PFS_PCR | R_PFS_ISEL)}
#define GPIO_IRQ12_P008_DS                      (gpio_pinset_t){ PORT0, PIN8, (GPIO_INPUT | R_PFS_PCR | R_PFS_ISEL)}
#define GPIO_IRQ12_P801                      (gpio_pinset_t){ PORT8, PIN1, (GPIO_INPUT | R_PFS_PCR | R_PFS_ISEL)}
#define GPIO_IRQ13_P009_DS                      (gpio_pinset_t){ PORT0, PIN9, (GPIO_INPUT | R_PFS_PCR | R_PFS_ISEL)}
#define GPIO_IRQ13_P015                      (gpio_pinset_t){ PORT0, PIN15, (GPIO_INPUT | R_PFS_PCR | R_PFS_ISEL)}
#define GPIO_IRQ14_P010                      (gpio_pinset_t){ PORT0, PIN10, (GPIO_INPUT | R_PFS_PCR | R_PFS_ISEL)}
#define GPIO_IRQ14_P403_DS                      (gpio_pinset_t){ PORT4, PIN3, (GPIO_INPUT | R_PFS_PCR | R_PFS_ISEL)}
#define GPIO_IRQ14_P512                      (gpio_pinset_t){ PORT5, PIN12, (GPIO_INPUT | R_PFS_PCR | R_PFS_ISEL)}
#define GPIO_IRQ14_P804                      (gpio_pinset_t){ PORT8, PIN4, (GPIO_INPUT | R_PFS_PCR | R_PFS_ISEL)}
#define GPIO_IRQ15_P404_DS                      (gpio_pinset_t){ PORT4, PIN4, (GPIO_INPUT | R_PFS_PCR | R_PFS_ISEL)}
#define GPIO_IRQ15_P511                      (gpio_pinset_t){ PORT5, PIN11, (GPIO_INPUT | R_PFS_PCR | R_PFS_ISEL)}
#define GPIO_IRQ15_P808                      (gpio_pinset_t){ PORT8, PIN8, (GPIO_INPUT | R_PFS_PCR | R_PFS_ISEL)}
#define GPIO_IRQ1_P101                      (gpio_pinset_t){ PORT1, PIN1, (GPIO_INPUT | R_PFS_PCR | R_PFS_ISEL)}
#define GPIO_IRQ1_P104                      (gpio_pinset_t){ PORT1, PIN4, (GPIO_INPUT | R_PFS_PCR | R_PFS_ISEL)}
#define GPIO_IRQ1_P205_DS                      (gpio_pinset_t){ PORT2, PIN5, (GPIO_INPUT | R_PFS_PCR | R_PFS_ISEL)}
#define GPIO_IRQ2_P100                      (gpio_pinset_t){ PORT1, PIN0, (GPIO_INPUT | R_PFS_PCR | R_PFS_ISEL)}
#define GPIO_IRQ2_P203_DS                      (gpio_pinset_t){ PORT2, PIN3, (GPIO_INPUT | R_PFS_PCR | R_PFS_ISEL)}
#define GPIO_IRQ2_P213                      (gpio_pinset_t){ PORT2, PIN13, (GPIO_INPUT | R_PFS_PCR | R_PFS_ISEL)}
#define GPIO_IRQ3_P202_DS                      (gpio_pinset_t){ PORT2, PIN2, (GPIO_INPUT | R_PFS_PCR | R_PFS_ISEL)}
#define GPIO_IRQ3_P208                      (gpio_pinset_t){ PORT2, PIN8, (GPIO_INPUT | R_PFS_PCR | R_PFS_ISEL)}
#define GPIO_IRQ3_P212                      (gpio_pinset_t){ PORT2, PIN12, (GPIO_INPUT | R_PFS_PCR | R_PFS_ISEL)}
#define GPIO_IRQ4_P300                      (gpio_pinset_t){ PORT3, PIN0, (GPIO_INPUT | R_PFS_PCR | R_PFS_ISEL)}
#define GPIO_IRQ4_P402_DS                      (gpio_pinset_t){ PORT4, PIN2, (GPIO_INPUT | R_PFS_PCR | R_PFS_ISEL)}
#define GPIO_IRQ4_P411                      (gpio_pinset_t){ PORT4, PIN11, (GPIO_INPUT | R_PFS_PCR | R_PFS_ISEL)}
#define GPIO_IRQ5_P302                      (gpio_pinset_t){ PORT3, PIN2, (GPIO_INPUT | R_PFS_PCR | R_PFS_ISEL)}
#define GPIO_IRQ5_P401_DS                      (gpio_pinset_t){ PORT4, PIN1, (GPIO_INPUT | R_PFS_PCR | R_PFS_ISEL)}
#define GPIO_IRQ5_P410                      (gpio_pinset_t){ PORT4, PIN10, (GPIO_INPUT | R_PFS_PCR | R_PFS_ISEL)}
#define GPIO_IRQ6_P000_DS                      (gpio_pinset_t){ PORT0, PIN0, (GPIO_INPUT | R_PFS_PCR | R_PFS_ISEL)}
#define GPIO_IRQ6_P301                      (gpio_pinset_t){ PORT3, PIN1, (GPIO_INPUT | R_PFS_PCR | R_PFS_ISEL)}
#define GPIO_IRQ6_P409                      (gpio_pinset_t){ PORT4, PIN9, (GPIO_INPUT | R_PFS_PCR | R_PFS_ISEL)}
#define GPIO_IRQ7_P001_DS                      (gpio_pinset_t){ PORT0, PIN1, (GPIO_INPUT | R_PFS_PCR | R_PFS_ISEL)}
#define GPIO_IRQ7_P408                      (gpio_pinset_t){ PORT4, PIN8, (GPIO_INPUT | R_PFS_PCR | R_PFS_ISEL)}
#define GPIO_IRQ8_P002_DS                      (gpio_pinset_t){ PORT0, PIN2, (GPIO_INPUT | R_PFS_PCR | R_PFS_ISEL)}
#define GPIO_IRQ8_P305                      (gpio_pinset_t){ PORT3, PIN5, (GPIO_INPUT | R_PFS_PCR | R_PFS_ISEL)}
#define GPIO_IRQ8_P415                      (gpio_pinset_t){ PORT4, PIN15, (GPIO_INPUT | R_PFS_PCR | R_PFS_ISEL)}
#define GPIO_IRQ8_P905                      (gpio_pinset_t){ PORT9, PIN5, (GPIO_INPUT | R_PFS_PCR | R_PFS_ISEL)}
#define GPIO_IRQ9_P004_DS                      (gpio_pinset_t){ PORT0, PIN4, (GPIO_INPUT | R_PFS_PCR | R_PFS_ISEL)}
#define GPIO_IRQ9_P304                      (gpio_pinset_t){ PORT3, PIN4, (GPIO_INPUT | R_PFS_PCR | R_PFS_ISEL)}
#define GPIO_IRQ9_P414                      (gpio_pinset_t){ PORT4, PIN14, (GPIO_INPUT | R_PFS_PCR | R_PFS_ISEL)}

/* Analog Input Definitions */
#define GPIO_AN000 / IVCMP2_1                        (gpio_pinset_t){ PORT0, PIN4, (0 | R_PFS_ASEL)}
#define GPIO_AN001_1                        (gpio_pinset_t){ PORT0, PIN5, (0 | R_PFS_ASEL)}
#define GPIO_AN002 / IVCMP3_1                        (gpio_pinset_t){ PORT0, PIN6, (0 | R_PFS_ASEL)}
#define GPIO_AN004_1                        (gpio_pinset_t){ PORT0, PIN7, (0 | R_PFS_ASEL)}
#define GPIO_AN005 / IVCMP0_1                        (gpio_pinset_t){ PORT0, PIN10, (0 | R_PFS_ASEL)}
#define GPIO_AN006_1                        (gpio_pinset_t){ PORT0, PIN9, (0 | R_PFS_ASEL)}
#define GPIO_AN007 / DA0_1                        (gpio_pinset_t){ PORT0, PIN14, (0 | R_PFS_ASEL)}
#define GPIO_AN008_1                        (gpio_pinset_t){ PORT0, PIN8, (0 | R_PFS_ASEL)}
#define GPIO_AN100 / IVCMP2_1                        (gpio_pinset_t){ PORT0, PIN0, (0 | R_PFS_ASEL)}
#define GPIO_AN101 / IVREF0_1                        (gpio_pinset_t){ PORT0, PIN1, (0 | R_PFS_ASEL)}
#define GPIO_AN102 / IVCMP3_1                        (gpio_pinset_t){ PORT0, PIN2, (0 | R_PFS_ASEL)}
#define GPIO_AN104 / IVREF1_1                        (gpio_pinset_t){ PORT0, PIN3, (0 | R_PFS_ASEL)}
#define GPIO_AN105_1                        (gpio_pinset_t){ PORT0, PIN15, (0 | R_PFS_ASEL)}

/* General Purpose GPIO Pin Definitions */

/* P000 Pin Definitions */
#define GPIO_P000_OUTPUT_HIGH               (gpio_pinset_t){ PORT0, PIN0, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_HIGH)}
#define GPIO_P000_OUTPUT_LOW                (gpio_pinset_t){ PORT0, PIN0, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_LOW)}
#define GPIO_P000_INPUT                     (gpio_pinset_t){ PORT0, PIN0, (GPIO_INPUT)}
#define GPIO_P000_INPUT_PULLUP              (gpio_pinset_t){ PORT0, PIN0, (GPIO_INPUT | R_PFS_PCR)}
#define GPIO_P000_ANALOG                    (gpio_pinset_t){ PORT0, PIN0, (0 | R_PFS_ASEL)}

/* P001 Pin Definitions */
#define GPIO_P001_OUTPUT_HIGH               (gpio_pinset_t){ PORT0, PIN1, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_HIGH)}
#define GPIO_P001_OUTPUT_LOW                (gpio_pinset_t){ PORT0, PIN1, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_LOW)}
#define GPIO_P001_INPUT                     (gpio_pinset_t){ PORT0, PIN1, (GPIO_INPUT)}
#define GPIO_P001_INPUT_PULLUP              (gpio_pinset_t){ PORT0, PIN1, (GPIO_INPUT | R_PFS_PCR)}
#define GPIO_P001_ANALOG                    (gpio_pinset_t){ PORT0, PIN1, (0 | R_PFS_ASEL)}

/* P002 Pin Definitions */
#define GPIO_P002_OUTPUT_HIGH               (gpio_pinset_t){ PORT0, PIN2, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_HIGH)}
#define GPIO_P002_OUTPUT_LOW                (gpio_pinset_t){ PORT0, PIN2, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_LOW)}
#define GPIO_P002_INPUT                     (gpio_pinset_t){ PORT0, PIN2, (GPIO_INPUT)}
#define GPIO_P002_INPUT_PULLUP              (gpio_pinset_t){ PORT0, PIN2, (GPIO_INPUT | R_PFS_PCR)}
#define GPIO_P002_ANALOG                    (gpio_pinset_t){ PORT0, PIN2, (0 | R_PFS_ASEL)}

/* P003 Pin Definitions */
#define GPIO_P003_OUTPUT_HIGH               (gpio_pinset_t){ PORT0, PIN3, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_HIGH)}
#define GPIO_P003_OUTPUT_LOW                (gpio_pinset_t){ PORT0, PIN3, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_LOW)}
#define GPIO_P003_INPUT                     (gpio_pinset_t){ PORT0, PIN3, (GPIO_INPUT)}
#define GPIO_P003_INPUT_PULLUP              (gpio_pinset_t){ PORT0, PIN3, (GPIO_INPUT | R_PFS_PCR)}
#define GPIO_P003_ANALOG                    (gpio_pinset_t){ PORT0, PIN3, (0 | R_PFS_ASEL)}

/* P004 Pin Definitions */
#define GPIO_P004_OUTPUT_HIGH               (gpio_pinset_t){ PORT0, PIN4, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_HIGH)}
#define GPIO_P004_OUTPUT_LOW                (gpio_pinset_t){ PORT0, PIN4, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_LOW)}
#define GPIO_P004_INPUT                     (gpio_pinset_t){ PORT0, PIN4, (GPIO_INPUT)}
#define GPIO_P004_INPUT_PULLUP              (gpio_pinset_t){ PORT0, PIN4, (GPIO_INPUT | R_PFS_PCR)}
#define GPIO_P004_ANALOG                    (gpio_pinset_t){ PORT0, PIN4, (0 | R_PFS_ASEL)}

/* P005 Pin Definitions */
#define GPIO_P005_OUTPUT_HIGH               (gpio_pinset_t){ PORT0, PIN5, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_HIGH)}
#define GPIO_P005_OUTPUT_LOW                (gpio_pinset_t){ PORT0, PIN5, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_LOW)}
#define GPIO_P005_INPUT                     (gpio_pinset_t){ PORT0, PIN5, (GPIO_INPUT)}
#define GPIO_P005_INPUT_PULLUP              (gpio_pinset_t){ PORT0, PIN5, (GPIO_INPUT | R_PFS_PCR)}
#define GPIO_P005_ANALOG                    (gpio_pinset_t){ PORT0, PIN5, (0 | R_PFS_ASEL)}

/* P006 Pin Definitions */
#define GPIO_P006_OUTPUT_HIGH               (gpio_pinset_t){ PORT0, PIN6, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_HIGH)}
#define GPIO_P006_OUTPUT_LOW                (gpio_pinset_t){ PORT0, PIN6, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_LOW)}
#define GPIO_P006_INPUT                     (gpio_pinset_t){ PORT0, PIN6, (GPIO_INPUT)}
#define GPIO_P006_INPUT_PULLUP              (gpio_pinset_t){ PORT0, PIN6, (GPIO_INPUT | R_PFS_PCR)}
#define GPIO_P006_ANALOG                    (gpio_pinset_t){ PORT0, PIN6, (0 | R_PFS_ASEL)}

/* P007 Pin Definitions */
#define GPIO_P007_OUTPUT_HIGH               (gpio_pinset_t){ PORT0, PIN7, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_HIGH)}
#define GPIO_P007_OUTPUT_LOW                (gpio_pinset_t){ PORT0, PIN7, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_LOW)}
#define GPIO_P007_INPUT                     (gpio_pinset_t){ PORT0, PIN7, (GPIO_INPUT)}
#define GPIO_P007_INPUT_PULLUP              (gpio_pinset_t){ PORT0, PIN7, (GPIO_INPUT | R_PFS_PCR)}
#define GPIO_P007_ANALOG                    (gpio_pinset_t){ PORT0, PIN7, (0 | R_PFS_ASEL)}

/* P008 Pin Definitions */
#define GPIO_P008_OUTPUT_HIGH               (gpio_pinset_t){ PORT0, PIN8, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_HIGH)}
#define GPIO_P008_OUTPUT_LOW                (gpio_pinset_t){ PORT0, PIN8, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_LOW)}
#define GPIO_P008_INPUT                     (gpio_pinset_t){ PORT0, PIN8, (GPIO_INPUT)}
#define GPIO_P008_INPUT_PULLUP              (gpio_pinset_t){ PORT0, PIN8, (GPIO_INPUT | R_PFS_PCR)}
#define GPIO_P008_ANALOG                    (gpio_pinset_t){ PORT0, PIN8, (0 | R_PFS_ASEL)}

/* P009 Pin Definitions */
#define GPIO_P009_OUTPUT_HIGH               (gpio_pinset_t){ PORT0, PIN9, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_HIGH)}
#define GPIO_P009_OUTPUT_LOW                (gpio_pinset_t){ PORT0, PIN9, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_LOW)}
#define GPIO_P009_INPUT                     (gpio_pinset_t){ PORT0, PIN9, (GPIO_INPUT)}
#define GPIO_P009_INPUT_PULLUP              (gpio_pinset_t){ PORT0, PIN9, (GPIO_INPUT | R_PFS_PCR)}
#define GPIO_P009_ANALOG                    (gpio_pinset_t){ PORT0, PIN9, (0 | R_PFS_ASEL)}

/* P010 Pin Definitions */
#define GPIO_P010_OUTPUT_HIGH               (gpio_pinset_t){ PORT0, PIN10, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_HIGH)}
#define GPIO_P010_OUTPUT_LOW                (gpio_pinset_t){ PORT0, PIN10, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_LOW)}
#define GPIO_P010_INPUT                     (gpio_pinset_t){ PORT0, PIN10, (GPIO_INPUT)}
#define GPIO_P010_INPUT_PULLUP              (gpio_pinset_t){ PORT0, PIN10, (GPIO_INPUT | R_PFS_PCR)}
#define GPIO_P010_ANALOG                    (gpio_pinset_t){ PORT0, PIN10, (0 | R_PFS_ASEL)}

/* P014 Pin Definitions */
#define GPIO_P014_OUTPUT_HIGH               (gpio_pinset_t){ PORT0, PIN14, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_HIGH)}
#define GPIO_P014_OUTPUT_LOW                (gpio_pinset_t){ PORT0, PIN14, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_LOW)}
#define GPIO_P014_INPUT                     (gpio_pinset_t){ PORT0, PIN14, (GPIO_INPUT)}
#define GPIO_P014_INPUT_PULLUP              (gpio_pinset_t){ PORT0, PIN14, (GPIO_INPUT | R_PFS_PCR)}
#define GPIO_P014_ANALOG                    (gpio_pinset_t){ PORT0, PIN14, (0 | R_PFS_ASEL)}

/* P015 Pin Definitions */
#define GPIO_P015_OUTPUT_HIGH               (gpio_pinset_t){ PORT0, PIN15, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_HIGH)}
#define GPIO_P015_OUTPUT_LOW                (gpio_pinset_t){ PORT0, PIN15, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_LOW)}
#define GPIO_P015_INPUT                     (gpio_pinset_t){ PORT0, PIN15, (GPIO_INPUT)}
#define GPIO_P015_INPUT_PULLUP              (gpio_pinset_t){ PORT0, PIN15, (GPIO_INPUT | R_PFS_PCR)}
#define GPIO_P015_ANALOG                    (gpio_pinset_t){ PORT0, PIN15, (0 | R_PFS_ASEL)}

/* P100 Pin Definitions */
#define GPIO_P100_OUTPUT_HIGH               (gpio_pinset_t){ PORT1, PIN0, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_HIGH)}
#define GPIO_P100_OUTPUT_LOW                (gpio_pinset_t){ PORT1, PIN0, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_LOW)}
#define GPIO_P100_INPUT                     (gpio_pinset_t){ PORT1, PIN0, (GPIO_INPUT)}
#define GPIO_P100_INPUT_PULLUP              (gpio_pinset_t){ PORT1, PIN0, (GPIO_INPUT | R_PFS_PCR)}

/* P101 Pin Definitions */
#define GPIO_P101_OUTPUT_HIGH               (gpio_pinset_t){ PORT1, PIN1, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_HIGH)}
#define GPIO_P101_OUTPUT_LOW                (gpio_pinset_t){ PORT1, PIN1, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_LOW)}
#define GPIO_P101_INPUT                     (gpio_pinset_t){ PORT1, PIN1, (GPIO_INPUT)}
#define GPIO_P101_INPUT_PULLUP              (gpio_pinset_t){ PORT1, PIN1, (GPIO_INPUT | R_PFS_PCR)}

/* P102 Pin Definitions */
#define GPIO_P102_OUTPUT_HIGH               (gpio_pinset_t){ PORT1, PIN2, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_HIGH)}
#define GPIO_P102_OUTPUT_LOW                (gpio_pinset_t){ PORT1, PIN2, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_LOW)}
#define GPIO_P102_INPUT                     (gpio_pinset_t){ PORT1, PIN2, (GPIO_INPUT)}
#define GPIO_P102_INPUT_PULLUP              (gpio_pinset_t){ PORT1, PIN2, (GPIO_INPUT | R_PFS_PCR)}

/* P103 Pin Definitions */
#define GPIO_P103_OUTPUT_HIGH               (gpio_pinset_t){ PORT1, PIN3, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_HIGH)}
#define GPIO_P103_OUTPUT_LOW                (gpio_pinset_t){ PORT1, PIN3, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_LOW)}
#define GPIO_P103_INPUT                     (gpio_pinset_t){ PORT1, PIN3, (GPIO_INPUT)}
#define GPIO_P103_INPUT_PULLUP              (gpio_pinset_t){ PORT1, PIN3, (GPIO_INPUT | R_PFS_PCR)}

/* P104 Pin Definitions */
#define GPIO_P104_OUTPUT_HIGH               (gpio_pinset_t){ PORT1, PIN4, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_HIGH)}
#define GPIO_P104_OUTPUT_LOW                (gpio_pinset_t){ PORT1, PIN4, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_LOW)}
#define GPIO_P104_INPUT                     (gpio_pinset_t){ PORT1, PIN4, (GPIO_INPUT)}
#define GPIO_P104_INPUT_PULLUP              (gpio_pinset_t){ PORT1, PIN4, (GPIO_INPUT | R_PFS_PCR)}

/* P105 Pin Definitions */
#define GPIO_P105_OUTPUT_HIGH               (gpio_pinset_t){ PORT1, PIN5, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_HIGH)}
#define GPIO_P105_OUTPUT_LOW                (gpio_pinset_t){ PORT1, PIN5, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_LOW)}
#define GPIO_P105_INPUT                     (gpio_pinset_t){ PORT1, PIN5, (GPIO_INPUT)}
#define GPIO_P105_INPUT_PULLUP              (gpio_pinset_t){ PORT1, PIN5, (GPIO_INPUT | R_PFS_PCR)}

/* P106 Pin Definitions */
#define GPIO_P106_OUTPUT_HIGH               (gpio_pinset_t){ PORT1, PIN6, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_HIGH)}
#define GPIO_P106_OUTPUT_LOW                (gpio_pinset_t){ PORT1, PIN6, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_LOW)}
#define GPIO_P106_INPUT                     (gpio_pinset_t){ PORT1, PIN6, (GPIO_INPUT)}
#define GPIO_P106_INPUT_PULLUP              (gpio_pinset_t){ PORT1, PIN6, (GPIO_INPUT | R_PFS_PCR)}

/* P107 Pin Definitions */
#define GPIO_P107_OUTPUT_HIGH               (gpio_pinset_t){ PORT1, PIN7, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_HIGH)}
#define GPIO_P107_OUTPUT_LOW                (gpio_pinset_t){ PORT1, PIN7, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_LOW)}
#define GPIO_P107_INPUT                     (gpio_pinset_t){ PORT1, PIN7, (GPIO_INPUT)}
#define GPIO_P107_INPUT_PULLUP              (gpio_pinset_t){ PORT1, PIN7, (GPIO_INPUT | R_PFS_PCR)}

/* P112 Pin Definitions */
#define GPIO_P112_OUTPUT_HIGH               (gpio_pinset_t){ PORT1, PIN12, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_HIGH)}
#define GPIO_P112_OUTPUT_LOW                (gpio_pinset_t){ PORT1, PIN12, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_LOW)}
#define GPIO_P112_INPUT                     (gpio_pinset_t){ PORT1, PIN12, (GPIO_INPUT)}
#define GPIO_P112_INPUT_PULLUP              (gpio_pinset_t){ PORT1, PIN12, (GPIO_INPUT | R_PFS_PCR)}

/* P113 Pin Definitions */
#define GPIO_P113_OUTPUT_HIGH               (gpio_pinset_t){ PORT1, PIN13, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_HIGH)}
#define GPIO_P113_OUTPUT_LOW                (gpio_pinset_t){ PORT1, PIN13, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_LOW)}
#define GPIO_P113_INPUT                     (gpio_pinset_t){ PORT1, PIN13, (GPIO_INPUT)}
#define GPIO_P113_INPUT_PULLUP              (gpio_pinset_t){ PORT1, PIN13, (GPIO_INPUT | R_PFS_PCR)}

/* P114 Pin Definitions */
#define GPIO_P114_OUTPUT_HIGH               (gpio_pinset_t){ PORT1, PIN14, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_HIGH)}
#define GPIO_P114_OUTPUT_LOW                (gpio_pinset_t){ PORT1, PIN14, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_LOW)}
#define GPIO_P114_INPUT                     (gpio_pinset_t){ PORT1, PIN14, (GPIO_INPUT)}
#define GPIO_P114_INPUT_PULLUP              (gpio_pinset_t){ PORT1, PIN14, (GPIO_INPUT | R_PFS_PCR)}

/* P115 Pin Definitions */
#define GPIO_P115_OUTPUT_HIGH               (gpio_pinset_t){ PORT1, PIN15, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_HIGH)}
#define GPIO_P115_OUTPUT_LOW                (gpio_pinset_t){ PORT1, PIN15, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_LOW)}
#define GPIO_P115_INPUT                     (gpio_pinset_t){ PORT1, PIN15, (GPIO_INPUT)}
#define GPIO_P115_INPUT_PULLUP              (gpio_pinset_t){ PORT1, PIN15, (GPIO_INPUT | R_PFS_PCR)}

/* P200 Pin Definitions */
#define GPIO_P200_OUTPUT_HIGH               (gpio_pinset_t){ PORT2, PIN0, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_HIGH)}
#define GPIO_P200_OUTPUT_LOW                (gpio_pinset_t){ PORT2, PIN0, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_LOW)}
#define GPIO_P200_INPUT                     (gpio_pinset_t){ PORT2, PIN0, (GPIO_INPUT)}
#define GPIO_P200_INPUT_PULLUP              (gpio_pinset_t){ PORT2, PIN0, (GPIO_INPUT | R_PFS_PCR)}

/* P201 Pin Definitions */
#define GPIO_P201_OUTPUT_HIGH               (gpio_pinset_t){ PORT2, PIN1, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_HIGH)}
#define GPIO_P201_OUTPUT_LOW                (gpio_pinset_t){ PORT2, PIN1, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_LOW)}
#define GPIO_P201_INPUT                     (gpio_pinset_t){ PORT2, PIN1, (GPIO_INPUT)}
#define GPIO_P201_INPUT_PULLUP              (gpio_pinset_t){ PORT2, PIN1, (GPIO_INPUT | R_PFS_PCR)}

/* P202 Pin Definitions */
#define GPIO_P202_OUTPUT_HIGH               (gpio_pinset_t){ PORT2, PIN2, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_HIGH)}
#define GPIO_P202_OUTPUT_LOW                (gpio_pinset_t){ PORT2, PIN2, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_LOW)}
#define GPIO_P202_INPUT                     (gpio_pinset_t){ PORT2, PIN2, (GPIO_INPUT)}
#define GPIO_P202_INPUT_PULLUP              (gpio_pinset_t){ PORT2, PIN2, (GPIO_INPUT | R_PFS_PCR)}

/* P203 Pin Definitions */
#define GPIO_P203_OUTPUT_HIGH               (gpio_pinset_t){ PORT2, PIN3, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_HIGH)}
#define GPIO_P203_OUTPUT_LOW                (gpio_pinset_t){ PORT2, PIN3, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_LOW)}
#define GPIO_P203_INPUT                     (gpio_pinset_t){ PORT2, PIN3, (GPIO_INPUT)}
#define GPIO_P203_INPUT_PULLUP              (gpio_pinset_t){ PORT2, PIN3, (GPIO_INPUT | R_PFS_PCR)}

/* P204 Pin Definitions */
#define GPIO_P204_OUTPUT_HIGH               (gpio_pinset_t){ PORT2, PIN4, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_HIGH)}
#define GPIO_P204_OUTPUT_LOW                (gpio_pinset_t){ PORT2, PIN4, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_LOW)}
#define GPIO_P204_INPUT                     (gpio_pinset_t){ PORT2, PIN4, (GPIO_INPUT)}
#define GPIO_P204_INPUT_PULLUP              (gpio_pinset_t){ PORT2, PIN4, (GPIO_INPUT | R_PFS_PCR)}

/* P205 Pin Definitions */
#define GPIO_P205_OUTPUT_HIGH               (gpio_pinset_t){ PORT2, PIN5, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_HIGH)}
#define GPIO_P205_OUTPUT_LOW                (gpio_pinset_t){ PORT2, PIN5, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_LOW)}
#define GPIO_P205_INPUT                     (gpio_pinset_t){ PORT2, PIN5, (GPIO_INPUT)}
#define GPIO_P205_INPUT_PULLUP              (gpio_pinset_t){ PORT2, PIN5, (GPIO_INPUT | R_PFS_PCR)}

/* P206 Pin Definitions */
#define GPIO_P206_OUTPUT_HIGH               (gpio_pinset_t){ PORT2, PIN6, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_HIGH)}
#define GPIO_P206_OUTPUT_LOW                (gpio_pinset_t){ PORT2, PIN6, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_LOW)}
#define GPIO_P206_INPUT                     (gpio_pinset_t){ PORT2, PIN6, (GPIO_INPUT)}
#define GPIO_P206_INPUT_PULLUP              (gpio_pinset_t){ PORT2, PIN6, (GPIO_INPUT | R_PFS_PCR)}

/* P208 Pin Definitions */
#define GPIO_P208_OUTPUT_HIGH               (gpio_pinset_t){ PORT2, PIN8, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_HIGH)}
#define GPIO_P208_OUTPUT_LOW                (gpio_pinset_t){ PORT2, PIN8, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_LOW)}
#define GPIO_P208_INPUT                     (gpio_pinset_t){ PORT2, PIN8, (GPIO_INPUT)}
#define GPIO_P208_INPUT_PULLUP              (gpio_pinset_t){ PORT2, PIN8, (GPIO_INPUT | R_PFS_PCR)}

/* P209 Pin Definitions */
#define GPIO_P209_OUTPUT_HIGH               (gpio_pinset_t){ PORT2, PIN9, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_HIGH)}
#define GPIO_P209_OUTPUT_LOW                (gpio_pinset_t){ PORT2, PIN9, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_LOW)}
#define GPIO_P209_INPUT                     (gpio_pinset_t){ PORT2, PIN9, (GPIO_INPUT)}
#define GPIO_P209_INPUT_PULLUP              (gpio_pinset_t){ PORT2, PIN9, (GPIO_INPUT | R_PFS_PCR)}

/* P210 Pin Definitions */
#define GPIO_P210_OUTPUT_HIGH               (gpio_pinset_t){ PORT2, PIN10, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_HIGH)}
#define GPIO_P210_OUTPUT_LOW                (gpio_pinset_t){ PORT2, PIN10, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_LOW)}
#define GPIO_P210_INPUT                     (gpio_pinset_t){ PORT2, PIN10, (GPIO_INPUT)}
#define GPIO_P210_INPUT_PULLUP              (gpio_pinset_t){ PORT2, PIN10, (GPIO_INPUT | R_PFS_PCR)}

/* P211 Pin Definitions */
#define GPIO_P211_OUTPUT_HIGH               (gpio_pinset_t){ PORT2, PIN11, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_HIGH)}
#define GPIO_P211_OUTPUT_LOW                (gpio_pinset_t){ PORT2, PIN11, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_LOW)}
#define GPIO_P211_INPUT                     (gpio_pinset_t){ PORT2, PIN11, (GPIO_INPUT)}
#define GPIO_P211_INPUT_PULLUP              (gpio_pinset_t){ PORT2, PIN11, (GPIO_INPUT | R_PFS_PCR)}

/* P212 Pin Definitions */
#define GPIO_P212_OUTPUT_HIGH               (gpio_pinset_t){ PORT2, PIN12, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_HIGH)}
#define GPIO_P212_OUTPUT_LOW                (gpio_pinset_t){ PORT2, PIN12, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_LOW)}
#define GPIO_P212_INPUT                     (gpio_pinset_t){ PORT2, PIN12, (GPIO_INPUT)}
#define GPIO_P212_INPUT_PULLUP              (gpio_pinset_t){ PORT2, PIN12, (GPIO_INPUT | R_PFS_PCR)}

/* P213 Pin Definitions */
#define GPIO_P213_OUTPUT_HIGH               (gpio_pinset_t){ PORT2, PIN13, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_HIGH)}
#define GPIO_P213_OUTPUT_LOW                (gpio_pinset_t){ PORT2, PIN13, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_LOW)}
#define GPIO_P213_INPUT                     (gpio_pinset_t){ PORT2, PIN13, (GPIO_INPUT)}
#define GPIO_P213_INPUT_PULLUP              (gpio_pinset_t){ PORT2, PIN13, (GPIO_INPUT | R_PFS_PCR)}

/* P300 Pin Definitions */
#define GPIO_P300_OUTPUT_HIGH               (gpio_pinset_t){ PORT3, PIN0, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_HIGH)}
#define GPIO_P300_OUTPUT_LOW                (gpio_pinset_t){ PORT3, PIN0, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_LOW)}
#define GPIO_P300_INPUT                     (gpio_pinset_t){ PORT3, PIN0, (GPIO_INPUT)}
#define GPIO_P300_INPUT_PULLUP              (gpio_pinset_t){ PORT3, PIN0, (GPIO_INPUT | R_PFS_PCR)}

/* P301 Pin Definitions */
#define GPIO_P301_OUTPUT_HIGH               (gpio_pinset_t){ PORT3, PIN1, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_HIGH)}
#define GPIO_P301_OUTPUT_LOW                (gpio_pinset_t){ PORT3, PIN1, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_LOW)}
#define GPIO_P301_INPUT                     (gpio_pinset_t){ PORT3, PIN1, (GPIO_INPUT)}
#define GPIO_P301_INPUT_PULLUP              (gpio_pinset_t){ PORT3, PIN1, (GPIO_INPUT | R_PFS_PCR)}

/* P302 Pin Definitions */
#define GPIO_P302_OUTPUT_HIGH               (gpio_pinset_t){ PORT3, PIN2, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_HIGH)}
#define GPIO_P302_OUTPUT_LOW                (gpio_pinset_t){ PORT3, PIN2, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_LOW)}
#define GPIO_P302_INPUT                     (gpio_pinset_t){ PORT3, PIN2, (GPIO_INPUT)}
#define GPIO_P302_INPUT_PULLUP              (gpio_pinset_t){ PORT3, PIN2, (GPIO_INPUT | R_PFS_PCR)}

/* P303 Pin Definitions */
#define GPIO_P303_OUTPUT_HIGH               (gpio_pinset_t){ PORT3, PIN3, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_HIGH)}
#define GPIO_P303_OUTPUT_LOW                (gpio_pinset_t){ PORT3, PIN3, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_LOW)}
#define GPIO_P303_INPUT                     (gpio_pinset_t){ PORT3, PIN3, (GPIO_INPUT)}
#define GPIO_P303_INPUT_PULLUP              (gpio_pinset_t){ PORT3, PIN3, (GPIO_INPUT | R_PFS_PCR)}

/* P304 Pin Definitions */
#define GPIO_P304_OUTPUT_HIGH               (gpio_pinset_t){ PORT3, PIN4, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_HIGH)}
#define GPIO_P304_OUTPUT_LOW                (gpio_pinset_t){ PORT3, PIN4, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_LOW)}
#define GPIO_P304_INPUT                     (gpio_pinset_t){ PORT3, PIN4, (GPIO_INPUT)}
#define GPIO_P304_INPUT_PULLUP              (gpio_pinset_t){ PORT3, PIN4, (GPIO_INPUT | R_PFS_PCR)}

/* P305 Pin Definitions */
#define GPIO_P305_OUTPUT_HIGH               (gpio_pinset_t){ PORT3, PIN5, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_HIGH)}
#define GPIO_P305_OUTPUT_LOW                (gpio_pinset_t){ PORT3, PIN5, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_LOW)}
#define GPIO_P305_INPUT                     (gpio_pinset_t){ PORT3, PIN5, (GPIO_INPUT)}
#define GPIO_P305_INPUT_PULLUP              (gpio_pinset_t){ PORT3, PIN5, (GPIO_INPUT | R_PFS_PCR)}

/* P306 Pin Definitions */
#define GPIO_P306_OUTPUT_HIGH               (gpio_pinset_t){ PORT3, PIN6, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_HIGH)}
#define GPIO_P306_OUTPUT_LOW                (gpio_pinset_t){ PORT3, PIN6, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_LOW)}
#define GPIO_P306_INPUT                     (gpio_pinset_t){ PORT3, PIN6, (GPIO_INPUT)}
#define GPIO_P306_INPUT_PULLUP              (gpio_pinset_t){ PORT3, PIN6, (GPIO_INPUT | R_PFS_PCR)}

/* P307 Pin Definitions */
#define GPIO_P307_OUTPUT_HIGH               (gpio_pinset_t){ PORT3, PIN7, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_HIGH)}
#define GPIO_P307_OUTPUT_LOW                (gpio_pinset_t){ PORT3, PIN7, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_LOW)}
#define GPIO_P307_INPUT                     (gpio_pinset_t){ PORT3, PIN7, (GPIO_INPUT)}
#define GPIO_P307_INPUT_PULLUP              (gpio_pinset_t){ PORT3, PIN7, (GPIO_INPUT | R_PFS_PCR)}

/* P308 Pin Definitions */
#define GPIO_P308_OUTPUT_HIGH               (gpio_pinset_t){ PORT3, PIN8, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_HIGH)}
#define GPIO_P308_OUTPUT_LOW                (gpio_pinset_t){ PORT3, PIN8, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_LOW)}
#define GPIO_P308_INPUT                     (gpio_pinset_t){ PORT3, PIN8, (GPIO_INPUT)}
#define GPIO_P308_INPUT_PULLUP              (gpio_pinset_t){ PORT3, PIN8, (GPIO_INPUT | R_PFS_PCR)}

/* P309 Pin Definitions */
#define GPIO_P309_OUTPUT_HIGH               (gpio_pinset_t){ PORT3, PIN9, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_HIGH)}
#define GPIO_P309_OUTPUT_LOW                (gpio_pinset_t){ PORT3, PIN9, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_LOW)}
#define GPIO_P309_INPUT                     (gpio_pinset_t){ PORT3, PIN9, (GPIO_INPUT)}
#define GPIO_P309_INPUT_PULLUP              (gpio_pinset_t){ PORT3, PIN9, (GPIO_INPUT | R_PFS_PCR)}

/* P310 Pin Definitions */
#define GPIO_P310_OUTPUT_HIGH               (gpio_pinset_t){ PORT3, PIN10, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_HIGH)}
#define GPIO_P310_OUTPUT_LOW                (gpio_pinset_t){ PORT3, PIN10, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_LOW)}
#define GPIO_P310_INPUT                     (gpio_pinset_t){ PORT3, PIN10, (GPIO_INPUT)}
#define GPIO_P310_INPUT_PULLUP              (gpio_pinset_t){ PORT3, PIN10, (GPIO_INPUT | R_PFS_PCR)}

/* P311 Pin Definitions */
#define GPIO_P311_OUTPUT_HIGH               (gpio_pinset_t){ PORT3, PIN11, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_HIGH)}
#define GPIO_P311_OUTPUT_LOW                (gpio_pinset_t){ PORT3, PIN11, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_LOW)}
#define GPIO_P311_INPUT                     (gpio_pinset_t){ PORT3, PIN11, (GPIO_INPUT)}
#define GPIO_P311_INPUT_PULLUP              (gpio_pinset_t){ PORT3, PIN11, (GPIO_INPUT | R_PFS_PCR)}

/* P312 Pin Definitions */
#define GPIO_P312_OUTPUT_HIGH               (gpio_pinset_t){ PORT3, PIN12, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_HIGH)}
#define GPIO_P312_OUTPUT_LOW                (gpio_pinset_t){ PORT3, PIN12, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_LOW)}
#define GPIO_P312_INPUT                     (gpio_pinset_t){ PORT3, PIN12, (GPIO_INPUT)}
#define GPIO_P312_INPUT_PULLUP              (gpio_pinset_t){ PORT3, PIN12, (GPIO_INPUT | R_PFS_PCR)}

/* P313 Pin Definitions */
#define GPIO_P313_OUTPUT_HIGH               (gpio_pinset_t){ PORT3, PIN13, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_HIGH)}
#define GPIO_P313_OUTPUT_LOW                (gpio_pinset_t){ PORT3, PIN13, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_LOW)}
#define GPIO_P313_INPUT                     (gpio_pinset_t){ PORT3, PIN13, (GPIO_INPUT)}
#define GPIO_P313_INPUT_PULLUP              (gpio_pinset_t){ PORT3, PIN13, (GPIO_INPUT | R_PFS_PCR)}

/* P400 Pin Definitions */
#define GPIO_P400_OUTPUT_HIGH               (gpio_pinset_t){ PORT4, PIN0, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_HIGH)}
#define GPIO_P400_OUTPUT_LOW                (gpio_pinset_t){ PORT4, PIN0, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_LOW)}
#define GPIO_P400_INPUT                     (gpio_pinset_t){ PORT4, PIN0, (GPIO_INPUT)}
#define GPIO_P400_INPUT_PULLUP              (gpio_pinset_t){ PORT4, PIN0, (GPIO_INPUT | R_PFS_PCR)}

/* P401 Pin Definitions */
#define GPIO_P401_OUTPUT_HIGH               (gpio_pinset_t){ PORT4, PIN1, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_HIGH)}
#define GPIO_P401_OUTPUT_LOW                (gpio_pinset_t){ PORT4, PIN1, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_LOW)}
#define GPIO_P401_INPUT                     (gpio_pinset_t){ PORT4, PIN1, (GPIO_INPUT)}
#define GPIO_P401_INPUT_PULLUP              (gpio_pinset_t){ PORT4, PIN1, (GPIO_INPUT | R_PFS_PCR)}

/* P402 Pin Definitions */
#define GPIO_P402_OUTPUT_HIGH               (gpio_pinset_t){ PORT4, PIN2, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_HIGH)}
#define GPIO_P402_OUTPUT_LOW                (gpio_pinset_t){ PORT4, PIN2, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_LOW)}
#define GPIO_P402_INPUT                     (gpio_pinset_t){ PORT4, PIN2, (GPIO_INPUT)}
#define GPIO_P402_INPUT_PULLUP              (gpio_pinset_t){ PORT4, PIN2, (GPIO_INPUT | R_PFS_PCR)}

/* P403 Pin Definitions */
#define GPIO_P403_OUTPUT_HIGH               (gpio_pinset_t){ PORT4, PIN3, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_HIGH)}
#define GPIO_P403_OUTPUT_LOW                (gpio_pinset_t){ PORT4, PIN3, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_LOW)}
#define GPIO_P403_INPUT                     (gpio_pinset_t){ PORT4, PIN3, (GPIO_INPUT)}
#define GPIO_P403_INPUT_PULLUP              (gpio_pinset_t){ PORT4, PIN3, (GPIO_INPUT | R_PFS_PCR)}

/* P404 Pin Definitions */
#define GPIO_P404_OUTPUT_HIGH               (gpio_pinset_t){ PORT4, PIN4, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_HIGH)}
#define GPIO_P404_OUTPUT_LOW                (gpio_pinset_t){ PORT4, PIN4, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_LOW)}
#define GPIO_P404_INPUT                     (gpio_pinset_t){ PORT4, PIN4, (GPIO_INPUT)}
#define GPIO_P404_INPUT_PULLUP              (gpio_pinset_t){ PORT4, PIN4, (GPIO_INPUT | R_PFS_PCR)}

/* P405 Pin Definitions */
#define GPIO_P405_OUTPUT_HIGH               (gpio_pinset_t){ PORT4, PIN5, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_HIGH)}
#define GPIO_P405_OUTPUT_LOW                (gpio_pinset_t){ PORT4, PIN5, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_LOW)}
#define GPIO_P405_INPUT                     (gpio_pinset_t){ PORT4, PIN5, (GPIO_INPUT)}
#define GPIO_P405_INPUT_PULLUP              (gpio_pinset_t){ PORT4, PIN5, (GPIO_INPUT | R_PFS_PCR)}

/* P406 Pin Definitions */
#define GPIO_P406_OUTPUT_HIGH               (gpio_pinset_t){ PORT4, PIN6, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_HIGH)}
#define GPIO_P406_OUTPUT_LOW                (gpio_pinset_t){ PORT4, PIN6, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_LOW)}
#define GPIO_P406_INPUT                     (gpio_pinset_t){ PORT4, PIN6, (GPIO_INPUT)}
#define GPIO_P406_INPUT_PULLUP              (gpio_pinset_t){ PORT4, PIN6, (GPIO_INPUT | R_PFS_PCR)}

/* P407 Pin Definitions */
#define GPIO_P407_OUTPUT_HIGH               (gpio_pinset_t){ PORT4, PIN7, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_HIGH)}
#define GPIO_P407_OUTPUT_LOW                (gpio_pinset_t){ PORT4, PIN7, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_LOW)}
#define GPIO_P407_INPUT                     (gpio_pinset_t){ PORT4, PIN7, (GPIO_INPUT)}
#define GPIO_P407_INPUT_PULLUP              (gpio_pinset_t){ PORT4, PIN7, (GPIO_INPUT | R_PFS_PCR)}

/* P408 Pin Definitions */
#define GPIO_P408_OUTPUT_HIGH               (gpio_pinset_t){ PORT4, PIN8, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_HIGH)}
#define GPIO_P408_OUTPUT_LOW                (gpio_pinset_t){ PORT4, PIN8, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_LOW)}
#define GPIO_P408_INPUT                     (gpio_pinset_t){ PORT4, PIN8, (GPIO_INPUT)}
#define GPIO_P408_INPUT_PULLUP              (gpio_pinset_t){ PORT4, PIN8, (GPIO_INPUT | R_PFS_PCR)}

/* P409 Pin Definitions */
#define GPIO_P409_OUTPUT_HIGH               (gpio_pinset_t){ PORT4, PIN9, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_HIGH)}
#define GPIO_P409_OUTPUT_LOW                (gpio_pinset_t){ PORT4, PIN9, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_LOW)}
#define GPIO_P409_INPUT                     (gpio_pinset_t){ PORT4, PIN9, (GPIO_INPUT)}
#define GPIO_P409_INPUT_PULLUP              (gpio_pinset_t){ PORT4, PIN9, (GPIO_INPUT | R_PFS_PCR)}

/* P410 Pin Definitions */
#define GPIO_P410_OUTPUT_HIGH               (gpio_pinset_t){ PORT4, PIN10, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_HIGH)}
#define GPIO_P410_OUTPUT_LOW                (gpio_pinset_t){ PORT4, PIN10, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_LOW)}
#define GPIO_P410_INPUT                     (gpio_pinset_t){ PORT4, PIN10, (GPIO_INPUT)}
#define GPIO_P410_INPUT_PULLUP              (gpio_pinset_t){ PORT4, PIN10, (GPIO_INPUT | R_PFS_PCR)}

/* P411 Pin Definitions */
#define GPIO_P411_OUTPUT_HIGH               (gpio_pinset_t){ PORT4, PIN11, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_HIGH)}
#define GPIO_P411_OUTPUT_LOW                (gpio_pinset_t){ PORT4, PIN11, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_LOW)}
#define GPIO_P411_INPUT                     (gpio_pinset_t){ PORT4, PIN11, (GPIO_INPUT)}
#define GPIO_P411_INPUT_PULLUP              (gpio_pinset_t){ PORT4, PIN11, (GPIO_INPUT | R_PFS_PCR)}

/* P412 Pin Definitions */
#define GPIO_P412_OUTPUT_HIGH               (gpio_pinset_t){ PORT4, PIN12, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_HIGH)}
#define GPIO_P412_OUTPUT_LOW                (gpio_pinset_t){ PORT4, PIN12, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_LOW)}
#define GPIO_P412_INPUT                     (gpio_pinset_t){ PORT4, PIN12, (GPIO_INPUT)}
#define GPIO_P412_INPUT_PULLUP              (gpio_pinset_t){ PORT4, PIN12, (GPIO_INPUT | R_PFS_PCR)}

/* P413 Pin Definitions */
#define GPIO_P413_OUTPUT_HIGH               (gpio_pinset_t){ PORT4, PIN13, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_HIGH)}
#define GPIO_P413_OUTPUT_LOW                (gpio_pinset_t){ PORT4, PIN13, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_LOW)}
#define GPIO_P413_INPUT                     (gpio_pinset_t){ PORT4, PIN13, (GPIO_INPUT)}
#define GPIO_P413_INPUT_PULLUP              (gpio_pinset_t){ PORT4, PIN13, (GPIO_INPUT | R_PFS_PCR)}

/* P414 Pin Definitions */
#define GPIO_P414_OUTPUT_HIGH               (gpio_pinset_t){ PORT4, PIN14, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_HIGH)}
#define GPIO_P414_OUTPUT_LOW                (gpio_pinset_t){ PORT4, PIN14, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_LOW)}
#define GPIO_P414_INPUT                     (gpio_pinset_t){ PORT4, PIN14, (GPIO_INPUT)}
#define GPIO_P414_INPUT_PULLUP              (gpio_pinset_t){ PORT4, PIN14, (GPIO_INPUT | R_PFS_PCR)}

/* P415 Pin Definitions */
#define GPIO_P415_OUTPUT_HIGH               (gpio_pinset_t){ PORT4, PIN15, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_HIGH)}
#define GPIO_P415_OUTPUT_LOW                (gpio_pinset_t){ PORT4, PIN15, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_LOW)}
#define GPIO_P415_INPUT                     (gpio_pinset_t){ PORT4, PIN15, (GPIO_INPUT)}
#define GPIO_P415_INPUT_PULLUP              (gpio_pinset_t){ PORT4, PIN15, (GPIO_INPUT | R_PFS_PCR)}

/* P511 Pin Definitions */
#define GPIO_P511_OUTPUT_HIGH               (gpio_pinset_t){ PORT5, PIN11, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_HIGH)}
#define GPIO_P511_OUTPUT_LOW                (gpio_pinset_t){ PORT5, PIN11, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_LOW)}
#define GPIO_P511_INPUT                     (gpio_pinset_t){ PORT5, PIN11, (GPIO_INPUT)}
#define GPIO_P511_INPUT_PULLUP              (gpio_pinset_t){ PORT5, PIN11, (GPIO_INPUT | R_PFS_PCR)}

/* P512 Pin Definitions */
#define GPIO_P512_OUTPUT_HIGH               (gpio_pinset_t){ PORT5, PIN12, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_HIGH)}
#define GPIO_P512_OUTPUT_LOW                (gpio_pinset_t){ PORT5, PIN12, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_LOW)}
#define GPIO_P512_INPUT                     (gpio_pinset_t){ PORT5, PIN12, (GPIO_INPUT)}
#define GPIO_P512_INPUT_PULLUP              (gpio_pinset_t){ PORT5, PIN12, (GPIO_INPUT | R_PFS_PCR)}

/* P513 Pin Definitions */
#define GPIO_P513_OUTPUT_HIGH               (gpio_pinset_t){ PORT5, PIN13, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_HIGH)}
#define GPIO_P513_OUTPUT_LOW                (gpio_pinset_t){ PORT5, PIN13, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_LOW)}
#define GPIO_P513_INPUT                     (gpio_pinset_t){ PORT5, PIN13, (GPIO_INPUT)}
#define GPIO_P513_INPUT_PULLUP              (gpio_pinset_t){ PORT5, PIN13, (GPIO_INPUT | R_PFS_PCR)}

/* P600 Pin Definitions */
#define GPIO_P600_OUTPUT_HIGH               (gpio_pinset_t){ PORT6, PIN0, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_HIGH)}
#define GPIO_P600_OUTPUT_LOW                (gpio_pinset_t){ PORT6, PIN0, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_LOW)}
#define GPIO_P600_INPUT                     (gpio_pinset_t){ PORT6, PIN0, (GPIO_INPUT)}
#define GPIO_P600_INPUT_PULLUP              (gpio_pinset_t){ PORT6, PIN0, (GPIO_INPUT | R_PFS_PCR)}

/* P601 Pin Definitions */
#define GPIO_P601_OUTPUT_HIGH               (gpio_pinset_t){ PORT6, PIN1, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_HIGH)}
#define GPIO_P601_OUTPUT_LOW                (gpio_pinset_t){ PORT6, PIN1, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_LOW)}
#define GPIO_P601_INPUT                     (gpio_pinset_t){ PORT6, PIN1, (GPIO_INPUT)}
#define GPIO_P601_INPUT_PULLUP              (gpio_pinset_t){ PORT6, PIN1, (GPIO_INPUT | R_PFS_PCR)}

/* P602 Pin Definitions */
#define GPIO_P602_OUTPUT_HIGH               (gpio_pinset_t){ PORT6, PIN2, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_HIGH)}
#define GPIO_P602_OUTPUT_LOW                (gpio_pinset_t){ PORT6, PIN2, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_LOW)}
#define GPIO_P602_INPUT                     (gpio_pinset_t){ PORT6, PIN2, (GPIO_INPUT)}
#define GPIO_P602_INPUT_PULLUP              (gpio_pinset_t){ PORT6, PIN2, (GPIO_INPUT | R_PFS_PCR)}

/* P603 Pin Definitions */
#define GPIO_P603_OUTPUT_HIGH               (gpio_pinset_t){ PORT6, PIN3, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_HIGH)}
#define GPIO_P603_OUTPUT_LOW                (gpio_pinset_t){ PORT6, PIN3, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_LOW)}
#define GPIO_P603_INPUT                     (gpio_pinset_t){ PORT6, PIN3, (GPIO_INPUT)}
#define GPIO_P603_INPUT_PULLUP              (gpio_pinset_t){ PORT6, PIN3, (GPIO_INPUT | R_PFS_PCR)}

/* P604 Pin Definitions */
#define GPIO_P604_OUTPUT_HIGH               (gpio_pinset_t){ PORT6, PIN4, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_HIGH)}
#define GPIO_P604_OUTPUT_LOW                (gpio_pinset_t){ PORT6, PIN4, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_LOW)}
#define GPIO_P604_INPUT                     (gpio_pinset_t){ PORT6, PIN4, (GPIO_INPUT)}
#define GPIO_P604_INPUT_PULLUP              (gpio_pinset_t){ PORT6, PIN4, (GPIO_INPUT | R_PFS_PCR)}

/* P605 Pin Definitions */
#define GPIO_P605_OUTPUT_HIGH               (gpio_pinset_t){ PORT6, PIN5, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_HIGH)}
#define GPIO_P605_OUTPUT_LOW                (gpio_pinset_t){ PORT6, PIN5, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_LOW)}
#define GPIO_P605_INPUT                     (gpio_pinset_t){ PORT6, PIN5, (GPIO_INPUT)}
#define GPIO_P605_INPUT_PULLUP              (gpio_pinset_t){ PORT6, PIN5, (GPIO_INPUT | R_PFS_PCR)}

/* P609 Pin Definitions */
#define GPIO_P609_OUTPUT_HIGH               (gpio_pinset_t){ PORT6, PIN9, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_HIGH)}
#define GPIO_P609_OUTPUT_LOW                (gpio_pinset_t){ PORT6, PIN9, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_LOW)}
#define GPIO_P609_INPUT                     (gpio_pinset_t){ PORT6, PIN9, (GPIO_INPUT)}
#define GPIO_P609_INPUT_PULLUP              (gpio_pinset_t){ PORT6, PIN9, (GPIO_INPUT | R_PFS_PCR)}

/* P610 Pin Definitions */
#define GPIO_P610_OUTPUT_HIGH               (gpio_pinset_t){ PORT6, PIN10, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_HIGH)}
#define GPIO_P610_OUTPUT_LOW                (gpio_pinset_t){ PORT6, PIN10, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_LOW)}
#define GPIO_P610_INPUT                     (gpio_pinset_t){ PORT6, PIN10, (GPIO_INPUT)}
#define GPIO_P610_INPUT_PULLUP              (gpio_pinset_t){ PORT6, PIN10, (GPIO_INPUT | R_PFS_PCR)}

/* P611 Pin Definitions */
#define GPIO_P611_OUTPUT_HIGH               (gpio_pinset_t){ PORT6, PIN11, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_HIGH)}
#define GPIO_P611_OUTPUT_LOW                (gpio_pinset_t){ PORT6, PIN11, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_LOW)}
#define GPIO_P611_INPUT                     (gpio_pinset_t){ PORT6, PIN11, (GPIO_INPUT)}
#define GPIO_P611_INPUT_PULLUP              (gpio_pinset_t){ PORT6, PIN11, (GPIO_INPUT | R_PFS_PCR)}

/* P612 Pin Definitions */
#define GPIO_P612_OUTPUT_HIGH               (gpio_pinset_t){ PORT6, PIN12, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_HIGH)}
#define GPIO_P612_OUTPUT_LOW                (gpio_pinset_t){ PORT6, PIN12, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_LOW)}
#define GPIO_P612_INPUT                     (gpio_pinset_t){ PORT6, PIN12, (GPIO_INPUT)}
#define GPIO_P612_INPUT_PULLUP              (gpio_pinset_t){ PORT6, PIN12, (GPIO_INPUT | R_PFS_PCR)}

/* P613 Pin Definitions */
#define GPIO_P613_OUTPUT_HIGH               (gpio_pinset_t){ PORT6, PIN13, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_HIGH)}
#define GPIO_P613_OUTPUT_LOW                (gpio_pinset_t){ PORT6, PIN13, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_LOW)}
#define GPIO_P613_INPUT                     (gpio_pinset_t){ PORT6, PIN13, (GPIO_INPUT)}
#define GPIO_P613_INPUT_PULLUP              (gpio_pinset_t){ PORT6, PIN13, (GPIO_INPUT | R_PFS_PCR)}

/* P614 Pin Definitions */
#define GPIO_P614_OUTPUT_HIGH               (gpio_pinset_t){ PORT6, PIN14, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_HIGH)}
#define GPIO_P614_OUTPUT_LOW                (gpio_pinset_t){ PORT6, PIN14, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_LOW)}
#define GPIO_P614_INPUT                     (gpio_pinset_t){ PORT6, PIN14, (GPIO_INPUT)}
#define GPIO_P614_INPUT_PULLUP              (gpio_pinset_t){ PORT6, PIN14, (GPIO_INPUT | R_PFS_PCR)}

/* P700 Pin Definitions */
#define GPIO_P700_OUTPUT_HIGH               (gpio_pinset_t){ PORT7, PIN0, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_HIGH)}
#define GPIO_P700_OUTPUT_LOW                (gpio_pinset_t){ PORT7, PIN0, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_LOW)}
#define GPIO_P700_INPUT                     (gpio_pinset_t){ PORT7, PIN0, (GPIO_INPUT)}
#define GPIO_P700_INPUT_PULLUP              (gpio_pinset_t){ PORT7, PIN0, (GPIO_INPUT | R_PFS_PCR)}

/* P701 Pin Definitions */
#define GPIO_P701_OUTPUT_HIGH               (gpio_pinset_t){ PORT7, PIN1, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_HIGH)}
#define GPIO_P701_OUTPUT_LOW                (gpio_pinset_t){ PORT7, PIN1, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_LOW)}
#define GPIO_P701_INPUT                     (gpio_pinset_t){ PORT7, PIN1, (GPIO_INPUT)}
#define GPIO_P701_INPUT_PULLUP              (gpio_pinset_t){ PORT7, PIN1, (GPIO_INPUT | R_PFS_PCR)}

/* P702 Pin Definitions */
#define GPIO_P702_OUTPUT_HIGH               (gpio_pinset_t){ PORT7, PIN2, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_HIGH)}
#define GPIO_P702_OUTPUT_LOW                (gpio_pinset_t){ PORT7, PIN2, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_LOW)}
#define GPIO_P702_INPUT                     (gpio_pinset_t){ PORT7, PIN2, (GPIO_INPUT)}
#define GPIO_P702_INPUT_PULLUP              (gpio_pinset_t){ PORT7, PIN2, (GPIO_INPUT | R_PFS_PCR)}

/* P703 Pin Definitions */
#define GPIO_P703_OUTPUT_HIGH               (gpio_pinset_t){ PORT7, PIN3, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_HIGH)}
#define GPIO_P703_OUTPUT_LOW                (gpio_pinset_t){ PORT7, PIN3, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_LOW)}
#define GPIO_P703_INPUT                     (gpio_pinset_t){ PORT7, PIN3, (GPIO_INPUT)}
#define GPIO_P703_INPUT_PULLUP              (gpio_pinset_t){ PORT7, PIN3, (GPIO_INPUT | R_PFS_PCR)}

/* P704 Pin Definitions */
#define GPIO_P704_OUTPUT_HIGH               (gpio_pinset_t){ PORT7, PIN4, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_HIGH)}
#define GPIO_P704_OUTPUT_LOW                (gpio_pinset_t){ PORT7, PIN4, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_LOW)}
#define GPIO_P704_INPUT                     (gpio_pinset_t){ PORT7, PIN4, (GPIO_INPUT)}
#define GPIO_P704_INPUT_PULLUP              (gpio_pinset_t){ PORT7, PIN4, (GPIO_INPUT | R_PFS_PCR)}

/* P705 Pin Definitions */
#define GPIO_P705_OUTPUT_HIGH               (gpio_pinset_t){ PORT7, PIN5, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_HIGH)}
#define GPIO_P705_OUTPUT_LOW                (gpio_pinset_t){ PORT7, PIN5, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_LOW)}
#define GPIO_P705_INPUT                     (gpio_pinset_t){ PORT7, PIN5, (GPIO_INPUT)}
#define GPIO_P705_INPUT_PULLUP              (gpio_pinset_t){ PORT7, PIN5, (GPIO_INPUT | R_PFS_PCR)}

/* P708 Pin Definitions */
#define GPIO_P708_OUTPUT_HIGH               (gpio_pinset_t){ PORT7, PIN8, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_HIGH)}
#define GPIO_P708_OUTPUT_LOW                (gpio_pinset_t){ PORT7, PIN8, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_LOW)}
#define GPIO_P708_INPUT                     (gpio_pinset_t){ PORT7, PIN8, (GPIO_INPUT)}
#define GPIO_P708_INPUT_PULLUP              (gpio_pinset_t){ PORT7, PIN8, (GPIO_INPUT | R_PFS_PCR)}

/* P709 Pin Definitions */
#define GPIO_P709_OUTPUT_HIGH               (gpio_pinset_t){ PORT7, PIN9, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_HIGH)}
#define GPIO_P709_OUTPUT_LOW                (gpio_pinset_t){ PORT7, PIN9, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_LOW)}
#define GPIO_P709_INPUT                     (gpio_pinset_t){ PORT7, PIN9, (GPIO_INPUT)}
#define GPIO_P709_INPUT_PULLUP              (gpio_pinset_t){ PORT7, PIN9, (GPIO_INPUT | R_PFS_PCR)}

/* P710 Pin Definitions */
#define GPIO_P710_OUTPUT_HIGH               (gpio_pinset_t){ PORT7, PIN10, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_HIGH)}
#define GPIO_P710_OUTPUT_LOW                (gpio_pinset_t){ PORT7, PIN10, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_LOW)}
#define GPIO_P710_INPUT                     (gpio_pinset_t){ PORT7, PIN10, (GPIO_INPUT)}
#define GPIO_P710_INPUT_PULLUP              (gpio_pinset_t){ PORT7, PIN10, (GPIO_INPUT | R_PFS_PCR)}

/* P711 Pin Definitions */
#define GPIO_P711_OUTPUT_HIGH               (gpio_pinset_t){ PORT7, PIN11, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_HIGH)}
#define GPIO_P711_OUTPUT_LOW                (gpio_pinset_t){ PORT7, PIN11, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_LOW)}
#define GPIO_P711_INPUT                     (gpio_pinset_t){ PORT7, PIN11, (GPIO_INPUT)}
#define GPIO_P711_INPUT_PULLUP              (gpio_pinset_t){ PORT7, PIN11, (GPIO_INPUT | R_PFS_PCR)}

/* P712 Pin Definitions */
#define GPIO_P712_OUTPUT_HIGH               (gpio_pinset_t){ PORT7, PIN12, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_HIGH)}
#define GPIO_P712_OUTPUT_LOW                (gpio_pinset_t){ PORT7, PIN12, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_LOW)}
#define GPIO_P712_INPUT                     (gpio_pinset_t){ PORT7, PIN12, (GPIO_INPUT)}
#define GPIO_P712_INPUT_PULLUP              (gpio_pinset_t){ PORT7, PIN12, (GPIO_INPUT | R_PFS_PCR)}

/* P713 Pin Definitions */
#define GPIO_P713_OUTPUT_HIGH               (gpio_pinset_t){ PORT7, PIN13, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_HIGH)}
#define GPIO_P713_OUTPUT_LOW                (gpio_pinset_t){ PORT7, PIN13, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_LOW)}
#define GPIO_P713_INPUT                     (gpio_pinset_t){ PORT7, PIN13, (GPIO_INPUT)}
#define GPIO_P713_INPUT_PULLUP              (gpio_pinset_t){ PORT7, PIN13, (GPIO_INPUT | R_PFS_PCR)}

/* P800 Pin Definitions */
#define GPIO_P800_OUTPUT_HIGH               (gpio_pinset_t){ PORT8, PIN0, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_HIGH)}
#define GPIO_P800_OUTPUT_LOW                (gpio_pinset_t){ PORT8, PIN0, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_LOW)}
#define GPIO_P800_INPUT                     (gpio_pinset_t){ PORT8, PIN0, (GPIO_INPUT)}
#define GPIO_P800_INPUT_PULLUP              (gpio_pinset_t){ PORT8, PIN0, (GPIO_INPUT | R_PFS_PCR)}

/* P801 Pin Definitions */
#define GPIO_P801_OUTPUT_HIGH               (gpio_pinset_t){ PORT8, PIN1, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_HIGH)}
#define GPIO_P801_OUTPUT_LOW                (gpio_pinset_t){ PORT8, PIN1, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_LOW)}
#define GPIO_P801_INPUT                     (gpio_pinset_t){ PORT8, PIN1, (GPIO_INPUT)}
#define GPIO_P801_INPUT_PULLUP              (gpio_pinset_t){ PORT8, PIN1, (GPIO_INPUT | R_PFS_PCR)}

/* P802 Pin Definitions */
#define GPIO_P802_OUTPUT_HIGH               (gpio_pinset_t){ PORT8, PIN2, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_HIGH)}
#define GPIO_P802_OUTPUT_LOW                (gpio_pinset_t){ PORT8, PIN2, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_LOW)}
#define GPIO_P802_INPUT                     (gpio_pinset_t){ PORT8, PIN2, (GPIO_INPUT)}
#define GPIO_P802_INPUT_PULLUP              (gpio_pinset_t){ PORT8, PIN2, (GPIO_INPUT | R_PFS_PCR)}

/* P803 Pin Definitions */
#define GPIO_P803_OUTPUT_HIGH               (gpio_pinset_t){ PORT8, PIN3, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_HIGH)}
#define GPIO_P803_OUTPUT_LOW                (gpio_pinset_t){ PORT8, PIN3, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_LOW)}
#define GPIO_P803_INPUT                     (gpio_pinset_t){ PORT8, PIN3, (GPIO_INPUT)}
#define GPIO_P803_INPUT_PULLUP              (gpio_pinset_t){ PORT8, PIN3, (GPIO_INPUT | R_PFS_PCR)}

/* P804 Pin Definitions */
#define GPIO_P804_OUTPUT_HIGH               (gpio_pinset_t){ PORT8, PIN4, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_HIGH)}
#define GPIO_P804_OUTPUT_LOW                (gpio_pinset_t){ PORT8, PIN4, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_LOW)}
#define GPIO_P804_INPUT                     (gpio_pinset_t){ PORT8, PIN4, (GPIO_INPUT)}
#define GPIO_P804_INPUT_PULLUP              (gpio_pinset_t){ PORT8, PIN4, (GPIO_INPUT | R_PFS_PCR)}

/* P805 Pin Definitions */
#define GPIO_P805_OUTPUT_HIGH               (gpio_pinset_t){ PORT8, PIN5, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_HIGH)}
#define GPIO_P805_OUTPUT_LOW                (gpio_pinset_t){ PORT8, PIN5, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_LOW)}
#define GPIO_P805_INPUT                     (gpio_pinset_t){ PORT8, PIN5, (GPIO_INPUT)}
#define GPIO_P805_INPUT_PULLUP              (gpio_pinset_t){ PORT8, PIN5, (GPIO_INPUT | R_PFS_PCR)}

/* P806 Pin Definitions */
#define GPIO_P806_OUTPUT_HIGH               (gpio_pinset_t){ PORT8, PIN6, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_HIGH)}
#define GPIO_P806_OUTPUT_LOW                (gpio_pinset_t){ PORT8, PIN6, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_LOW)}
#define GPIO_P806_INPUT                     (gpio_pinset_t){ PORT8, PIN6, (GPIO_INPUT)}
#define GPIO_P806_INPUT_PULLUP              (gpio_pinset_t){ PORT8, PIN6, (GPIO_INPUT | R_PFS_PCR)}

/* P808 Pin Definitions */
#define GPIO_P808_OUTPUT_HIGH               (gpio_pinset_t){ PORT8, PIN8, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_HIGH)}
#define GPIO_P808_OUTPUT_LOW                (gpio_pinset_t){ PORT8, PIN8, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_LOW)}
#define GPIO_P808_INPUT                     (gpio_pinset_t){ PORT8, PIN8, (GPIO_INPUT)}
#define GPIO_P808_INPUT_PULLUP              (gpio_pinset_t){ PORT8, PIN8, (GPIO_INPUT | R_PFS_PCR)}

/* P809 Pin Definitions */
#define GPIO_P809_OUTPUT_HIGH               (gpio_pinset_t){ PORT8, PIN9, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_HIGH)}
#define GPIO_P809_OUTPUT_LOW                (gpio_pinset_t){ PORT8, PIN9, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_LOW)}
#define GPIO_P809_INPUT                     (gpio_pinset_t){ PORT8, PIN9, (GPIO_INPUT)}
#define GPIO_P809_INPUT_PULLUP              (gpio_pinset_t){ PORT8, PIN9, (GPIO_INPUT | R_PFS_PCR)}

/* P814 Pin Definitions */
#define GPIO_P814_OUTPUT_HIGH               (gpio_pinset_t){ PORT8, PIN14, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_HIGH)}
#define GPIO_P814_OUTPUT_LOW                (gpio_pinset_t){ PORT8, PIN14, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_LOW)}
#define GPIO_P814_INPUT                     (gpio_pinset_t){ PORT8, PIN14, (GPIO_INPUT)}
#define GPIO_P814_INPUT_PULLUP              (gpio_pinset_t){ PORT8, PIN14, (GPIO_INPUT | R_PFS_PCR)}

/* P815 Pin Definitions */
#define GPIO_P815_OUTPUT_HIGH               (gpio_pinset_t){ PORT8, PIN15, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_HIGH)}
#define GPIO_P815_OUTPUT_LOW                (gpio_pinset_t){ PORT8, PIN15, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_LOW)}
#define GPIO_P815_INPUT                     (gpio_pinset_t){ PORT8, PIN15, (GPIO_INPUT)}
#define GPIO_P815_INPUT_PULLUP              (gpio_pinset_t){ PORT8, PIN15, (GPIO_INPUT | R_PFS_PCR)}

/* P905 Pin Definitions */
#define GPIO_P905_OUTPUT_HIGH               (gpio_pinset_t){ PORT9, PIN5, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_HIGH)}
#define GPIO_P905_OUTPUT_LOW                (gpio_pinset_t){ PORT9, PIN5, (GPIO_OUTPUT | GPIO_LOW_DRIVE | GPIO_OUTPUT_LOW)}
#define GPIO_P905_INPUT                     (gpio_pinset_t){ PORT9, PIN5, (GPIO_INPUT)}
#define GPIO_P905_INPUT_PULLUP              (gpio_pinset_t){ PORT9, PIN5, (GPIO_INPUT | R_PFS_PCR)}

/* GPIO Configuration */
#define GPIO_OUTPUT               R_PFS_PDR
#define GPIO_INPUT               ~(R_PFS_PDR | 0xFFFFFFFF)
#define GPIO_LOW_DRIVE          ~(R_PFS_DSCR | 0xFFFFFFFF)
#define GPIO_MIDDLE_DRIVE       R_PFS_DSCR
#define GPIO_OUTPUT_HIGH         R_PFS_PODR
#define GPIO_OUTPUT_LOW         ~(R_PFS_PODR | 0xFFFFFFFF)

#endif /* __ARCH_ARM_SRC_RA_HARDWARE_RA8E1_PINMAP_H */
